project = "enduro"

[[bins]]
name = "golangci-lint"
url = "https://github.com/golangci/golangci-lint"
version = "2.11.4"

[[bins]]
name = "goreleaser"
url = "https://github.com/goreleaser/goreleaser"
version = "2.15.2"

[[bins]]
name = "go-mod-outdated"
url = "https://github.com/psampaz/go-mod-outdated"
version = "0.9.0"

[[bins]]
name = "gotestsum"
url = "https://github.com/gotestyourself/gotestsum"
version = "1.13.0"

[[bins]]
name = "goa"
go_package = "goa.design/goa/v3/cmd/goa"
version = "3.26.0"

[[bins]]
name = "mockgen"
go_package = "go.uber.org/mock/mockgen"
version = "0.6.0"

[[bins]]
name = "temporal-cli"
url = "https://github.com/temporalio/cli"
version = "1.6.2"

[[bins]]
name = "jq"
url = "https://github.com/jqlang/jq"
version = "1.8.1"
