# Validate this file:
#   curl --data-binary @.codecov.yml https://codecov.io/validate

comment: off

coverage:
  status:
    project:
      default:
        threshold: 5%
        if_not_found: success
    patch:
      default:
        if_not_found: success

ignore:
- "hack"
- "ui"
- "website"
