version: "2"
linters:
  default: standard
  enable:
    - gosec
    - importas
    - intrange
    - misspell
  settings:
    importas:
      alias:
        - pkg: go.temporal.io/sdk/(\w+)
          alias: temporalsdk_$1
        - pkg: go.temporal.io/api/(\w+)
          alias: temporalapi_$1
      no-unaliased: true
      no-extra-aliases: false
    gosec:
      # TODO: these must be put back again.
      # They were excluded during the migration to golangci-lint.
      excludes:
        - G104
        - G115
        - G301
        - G302
        - G304
  exclusions:
    warn-unused: true
    generated: lax
    presets:
      - std-error-handling
    rules:
      - linters: [errcheck]
        path: _test\.go
      - linters: [staticcheck]
        path: internal/api/design
        text: "ST1001: " # dot imports are allowed in goa design files.
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      no-inline-comments: true
      no-prefix-comments: false
    gofumpt:
      extra-rules: true
  exclusions:
    warn-unused: true
    generated: lax
