run:
  deadline: 60s
  skip-dirs:
    - hack
    - website
    - ui

linters:
  enable:
    - misspell
    - gofumpt
    - importas
    - gci

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  gci:
    no-inline-comments: true
    no-prefix-comments: false
    sections:
      - standard
      - default
      - prefix(github.com/artefactual-labs/enduro)
    section-separators:
      - newLine
  importas:
    no-unaliased: true
    no-extra-aliases: false
    alias:
      - pkg: go.temporal.io/sdk/(\w+)
        alias: temporalsdk_$1
      - pkg: go.temporal.io/api/(\w+)
        alias: temporalapi_$1
