project_name: enduro

before:
  hooks:
  - make ui

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^website:'

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  flags:
  - -trimpath
  ldflags:
  - -X "main.buildTime={{.Date}}"
  - -X "main.gitCommit={{.Commit}}"
  - -X "main.version={{.Version}}"

archives:
- wrap_in_directory: true
  format: tar.gz
  name_template: >-
    {{ .ProjectName }}_
    {{- .Version }}_
    {{- title .Os }}-
    {{- if eq .Arch "amd64" }}64bit
    {{- else if eq .Arch "386" }}32bit
    {{- else }}{{ .Arch }}{{ end }}
  files:
  - LICENSE
  - README.md
  - enduro.toml

checksum:
  name_template: checksums.txt
  algorithm: sha256

milestones:
  - repo:
      owner: artefactual-labs
      name: enduro
    close: true
    fail_on_error: false
    name_template: "{{ .Tag }}" 
