project_name: enduro

before:
  hooks:
  - make ui

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^website:'

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  flags:
  - -trimpath
  ldflags:
  - -X "main.buildTime={{.Date}}"
  - -X "main.gitCommit={{.Commit}}"
  - -X "main.version={{.Version}}"

archives:
- wrap_in_directory: true
  format: tar.gz
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    linux: Linux
    amd64: 64bit
  files:
  - LICENSE
  - README.md
  - enduro.toml

checksum:
  name_template: checksums.txt
  algorithm: sha256
