# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: enduro
before:
  hooks:
    - make ui
release:
  github:
    owner: artefactual-labs
    name: enduro
changelog:
  use: github
  abbrev: 8
  groups: []
  filters:
    exclude:
      - "^docs:"
      - "^website:"
builds:
  - goos: [linux]
    goarch: [amd64]
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -extldflags="-static"
      - -X "main.buildTime={{.Date}}"
      - -X "main.gitCommit={{.Commit}}"
      - -X "main.version={{.Version}}"
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
archives:
  - wrap_in_directory: true
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - enduro.toml
checksum:
  name_template: checksums.txt
  algorithm: sha256
milestones:
  - repo:
      owner: artefactual-labs
      name: enduro
    close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"
