# Validate this file:
#   curl --data-binary @codecov.yml https://codecov.io/validate

# Threshold should not be as high once all packages are being tracked.

comment: off

coverage:
  precision: 2
  round: down
  range: "25...100"
  status:
    project:
      default:
        threshold: 25%
        if_not_found: success
    patch:
      default:
        threshold: 25%
        if_not_found: success

ignore:
- "build"
- "hack"
- "ui"
- "website"
- "fake"
- "gen"
