version: "3"

services:

  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_USER: "enduro"
      MYSQL_PASSWORD: "enduro123"
    volumes:
      - "./hack/docker-init-mysql.sql:/docker-entrypoint-initdb.d/docker-init.sql"
    ports:
      - "127.0.0.1:7450:3306"

  # temporal:
  #   image: "temporalio/auto-setup:1.21.1"
  #   environment:
  #     - "DB=mysql"
  #     - "DB_PORT=3306"
  #     - "MYSQL_USER=root"
  #     - "MYSQL_PWD=root123"
  #     - "MYSQL_SEEDS=mysql"
  #   ports:
  #     - "127.0.0.1:7233:7233"

  # temporal-admin-tools:
  #   environment:
  #     - "TEMPORAL_CLI_ADDRESS=temporal:7233"
  #   image: "temporalio/admin-tools:1.21.1"
  #   stdin_open: true
  #   tty: true

  # temporal-ui:
  #   image: "temporalio/ui:2.16.2"
  #   environment:
  #     - "TEMPORAL_ADDRESS=temporal:7233"
  #     - "TEMPORAL_CORS_ORIGINS=http://localhost:7440"
  #   ports:
  #     - "127.0.0.1:7440:8080"

  minio:
    image: "minio/minio:RELEASE.2020-04-28T23-56-56Z"
    command: "server /data"
    volumes:
      - "./hack/minio-data:/data"
    ports:
      - "127.0.0.1:7460:9000"

  redis:
    image: "redis:5-alpine"
    ports:
      - "127.0.0.1:7470:6379"
