version: "3"

services:

  mysql:
    image: "mysql:5.7"
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_USER: "enduro"
      MYSQL_PASSWORD: "enduro123"
    volumes:
      - "${PWD}/hack/docker-init-mysql.sql:/docker-entrypoint-initdb.d/docker-init.sql"
    ports:
      - "127.0.0.1:7450:3306"

  cadence:
    image: "ubercadence/server:0.9.5"
    command: ["cadence-server", "--root=/etc/cadence", "--env=docker", "start", "--services=frontend,matching,history,worker"]
    restart: "on-failure"
    ports:
      # frontend service
      - "127.0.0.1:7400:7400" # rpc
      - "127.0.0.1:7401:7401" # prom
      - "127.0.0.1:7402:7402" # pprof
      # matching service
      - "127.0.0.1:7410:7410" # rpc
      - "127.0.0.1:7411:7411" # prom
      - "127.0.0.1:7412:7412" # pprof
      # history service
      - "127.0.0.1:7420:7420" # rpc
      - "127.0.0.1:7421:7421" # prom
      - "127.0.0.1:7422:7422" # pprof
      # worker service
      - "127.0.0.1:7430:7430" # rpc
      - "127.0.0.1:7431:7431" # prom
      - "127.0.0.1:7432:7432" # pprof
    volumes:
      - "./hack/cadence/seed.sh:/seed.sh:ro"
      - "./hack/cadence/config.yml:/etc/cadence/config/docker.yaml:ro"

  cadence-web:
    image: "ubercadence/web:3.7.1"
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7400"
    ports:
      - "127.0.0.1:7440:8088"

  minio:
    image: "minio/minio:latest"
    command: "server /data"
    volumes:
      - "${PWD}/hack/minio-data:/data"
    ports:
      - "127.0.0.1:7460:9000"

  redis:
    image: "redis:5-alpine"
    ports:
      - "127.0.0.1:7470:6379"
