services:

  grafana:
    image: grafana/grafana:10.0.3
    volumes:
      - ./hack/etc/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "127.0.0.1:3000:3000"

  grafana-tempo:
    image: "grafana/tempo:latest"
    entrypoint:
      - "/tempo"
    command:
      - "-config.file=/etc/grafana-tempo.yaml"
    volumes:
      - "./hack/etc/grafana-tempo.yaml:/etc/grafana-tempo.yaml"
      - "./hack/stuff/tempo-data:/tmp/tempo"
    ports:
      - "127.0.0.1:4317:4317"

  grafana-agent:
    image: "grafana/agent:latest"
    entrypoint:
      - "/bin/grafana-agent"
    command:
      - "-config.file=/etc/grafana-agent.yaml"
    volumes:
      - "./hack/etc/grafana-agent.yaml:/etc/grafana-agent.yaml"
    ports:
      - "127.0.0.1:12345:4317"
