/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchConfigResponseBody
 */
export interface BatchConfigResponseBody {
    /**
     * 
     * @type {string}
     * @memberof BatchConfigResponseBody
     */
    completedDir?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchConfigResponseBody
     */
    retentionPeriod?: string;
}

export function BatchConfigResponseBodyFromJSON(json: any): BatchConfigResponseBody {
    return BatchConfigResponseBodyFromJSONTyped(json, false);
}

export function BatchConfigResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchConfigResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'completedDir': !exists(json, 'completed_dir') ? undefined : json['completed_dir'],
        'retentionPeriod': !exists(json, 'retention_period') ? undefined : json['retention_period'],
    };
}

export function BatchConfigResponseBodyToJSON(value?: BatchConfigResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'completed_dir': value.completedDir,
        'retention_period': value.retentionPeriod,
    };
}


