/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchResult
 */
export interface BatchResult {
    /**
     * 
     * @type {string}
     * @memberof BatchResult
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof BatchResult
     */
    workflowId: string;
}

/**
 * Check if a given object implements the BatchResult interface.
 */
export function instanceOfBatchResult(value: object): value is BatchResult {
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('workflowId' in value) || value['workflowId'] === undefined) return false;
    return true;
}

export function BatchResultFromJSON(json: any): BatchResult {
    return BatchResultFromJSONTyped(json, false);
}

export function BatchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['run_id'],
        'workflowId': json['workflow_id'],
    };
}

export function BatchResultToJSON(json: any): BatchResult {
    return BatchResultToJSONTyped(json, false);
}

export function BatchResultToJSONTyped(value?: BatchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['runId'],
        'workflow_id': value['workflowId'],
    };
}

