/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchBrowseEntry } from './BatchBrowseEntry';
import {
    BatchBrowseEntryFromJSON,
    BatchBrowseEntryFromJSONTyped,
    BatchBrowseEntryToJSON,
    BatchBrowseEntryToJSONTyped,
} from './BatchBrowseEntry';

/**
 * 
 * @export
 * @interface BatchBrowseResult
 */
export interface BatchBrowseResult {
    /**
     * Absolute path of the listed directory.
     * @type {string}
     * @memberof BatchBrowseResult
     */
    absolutePath: string;
    /**
     * Immediate child directories.
     * @type {Array<BatchBrowseEntry>}
     * @memberof BatchBrowseResult
     */
    entries: Array<BatchBrowseEntry>;
    /**
     * Root-relative path of the listed directory.
     * @type {string}
     * @memberof BatchBrowseResult
     */
    path: string;
    /**
     * Whether the result was truncated because it exceeded the entry limit.
     * @type {boolean}
     * @memberof BatchBrowseResult
     */
    truncated: boolean;
}

/**
 * Check if a given object implements the BatchBrowseResult interface.
 */
export function instanceOfBatchBrowseResult(value: object): value is BatchBrowseResult {
    if (!('absolutePath' in value) || value['absolutePath'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('truncated' in value) || value['truncated'] === undefined) return false;
    return true;
}

export function BatchBrowseResultFromJSON(json: any): BatchBrowseResult {
    return BatchBrowseResultFromJSONTyped(json, false);
}

export function BatchBrowseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchBrowseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'absolutePath': json['absolute_path'],
        'entries': ((json['entries'] as Array<any>).map(BatchBrowseEntryFromJSON)),
        'path': json['path'],
        'truncated': json['truncated'],
    };
}

export function BatchBrowseResultToJSON(json: any): BatchBrowseResult {
    return BatchBrowseResultToJSONTyped(json, false);
}

export function BatchBrowseResultToJSONTyped(value?: BatchBrowseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'absolute_path': value['absolutePath'],
        'entries': ((value['entries'] as Array<any>).map(BatchBrowseEntryToJSON)),
        'path': value['path'],
        'truncated': value['truncated'],
    };
}

