/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchHintsResult
 */
export interface BatchHintsResult {
    /**
     * A list of known values of completedDir used by existing watchers.
     * @type {Array<string>}
     * @memberof BatchHintsResult
     */
    completedDirs?: Array<string>;
}

/**
 * Check if a given object implements the BatchHintsResult interface.
 */
export function instanceOfBatchHintsResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BatchHintsResultFromJSON(json: any): BatchHintsResult {
    return BatchHintsResultFromJSONTyped(json, false);
}

export function BatchHintsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchHintsResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'completedDirs': !exists(json, 'completed_dirs') ? undefined : json['completed_dirs'],
    };
}

export function BatchHintsResultToJSON(value?: BatchHintsResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'completed_dirs': value.completedDirs,
    };
}

