/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchResult
 */
export interface BatchResult {
    /**
     * 
     * @type {string}
     * @memberof BatchResult
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof BatchResult
     */
    workflowId: string;
}

/**
 * Check if a given object implements the BatchResult interface.
 */
export function instanceOfBatchResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "runId" in value;
    isInstance = isInstance && "workflowId" in value;

    return isInstance;
}

export function BatchResultFromJSON(json: any): BatchResult {
    return BatchResultFromJSONTyped(json, false);
}

export function BatchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'runId': json['run_id'],
        'workflowId': json['workflow_id'],
    };
}

export function BatchResultToJSON(value?: BatchResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'run_id': value.runId,
        'workflow_id': value.workflowId,
    };
}

