/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchStatusResult
 */
export interface BatchStatusResult {
    /**
     * 
     * @type {string}
     * @memberof BatchStatusResult
     */
    runId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BatchStatusResult
     */
    running: boolean;
    /**
     * 
     * @type {string}
     * @memberof BatchStatusResult
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchStatusResult
     */
    workflowId?: string;
}

/**
 * Check if a given object implements the BatchStatusResult interface.
 */
export function instanceOfBatchStatusResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "running" in value;

    return isInstance;
}

export function BatchStatusResultFromJSON(json: any): BatchStatusResult {
    return BatchStatusResultFromJSONTyped(json, false);
}

export function BatchStatusResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchStatusResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'runId': !exists(json, 'run_id') ? undefined : json['run_id'],
        'running': json['running'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'workflowId': !exists(json, 'workflow_id') ? undefined : json['workflow_id'],
    };
}

export function BatchStatusResultToJSON(value?: BatchStatusResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'run_id': value.runId,
        'running': value.running,
        'status': value.status,
        'workflow_id': value.workflowId,
    };
}

