/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchStatusResult
 */
export interface BatchStatusResult {
    /**
     * 
     * @type {string}
     * @memberof BatchStatusResult
     */
    runId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BatchStatusResult
     */
    running: boolean;
    /**
     * 
     * @type {string}
     * @memberof BatchStatusResult
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchStatusResult
     */
    workflowId?: string;
}

/**
 * Check if a given object implements the BatchStatusResult interface.
 */
export function instanceOfBatchStatusResult(value: object): value is BatchStatusResult {
    if (!('running' in value) || value['running'] === undefined) return false;
    return true;
}

export function BatchStatusResultFromJSON(json: any): BatchStatusResult {
    return BatchStatusResultFromJSONTyped(json, false);
}

export function BatchStatusResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchStatusResult {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'running': json['running'],
        'status': json['status'] == null ? undefined : json['status'],
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
    };
}

export function BatchStatusResultToJSON(json: any): BatchStatusResult {
    return BatchStatusResultToJSONTyped(json, false);
}

export function BatchStatusResultToJSONTyped(value?: BatchStatusResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['runId'],
        'running': value['running'],
        'status': value['status'],
        'workflow_id': value['workflowId'],
    };
}

