/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Collection not found.
 * @export
 * @interface CollectionNotfound
 */
export interface CollectionNotfound {
    /**
     * Identifier of missing collection
     * @type {number}
     * @memberof CollectionNotfound
     */
    id: number;
    /**
     * Message of error
     * @type {string}
     * @memberof CollectionNotfound
     */
    message: string;
}

/**
 * Check if a given object implements the CollectionNotfound interface.
 */
export function instanceOfCollectionNotfound(value: object): value is CollectionNotfound {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CollectionNotfoundFromJSON(json: any): CollectionNotfound {
    return CollectionNotfoundFromJSONTyped(json, false);
}

export function CollectionNotfoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionNotfound {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
    };
}

export function CollectionNotfoundToJSON(json: any): CollectionNotfound {
    return CollectionNotfoundToJSONTyped(json, false);
}

export function CollectionNotfoundToJSONTyped(value?: CollectionNotfound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'message': value['message'],
    };
}

