/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Collection not found
 * @export
 * @interface CollectionNotfound
 */
export interface CollectionNotfound {
    /**
     * Identifier of missing collection
     * @type {number}
     * @memberof CollectionNotfound
     */
    id: number;
    /**
     * Message of error
     * @type {string}
     * @memberof CollectionNotfound
     */
    message: string;
}

/**
 * Check if a given object implements the CollectionNotfound interface.
 */
export function instanceOfCollectionNotfound(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function CollectionNotfoundFromJSON(json: any): CollectionNotfound {
    return CollectionNotfoundFromJSONTyped(json, false);
}

export function CollectionNotfoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionNotfound {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
    };
}

export function CollectionNotfoundToJSON(value?: CollectionNotfound | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'message': value.message,
    };
}

