/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionDecideRequest
 */
export interface CollectionDecideRequest {
    /**
     * Decision option to proceed with
     * @type {string}
     * @memberof CollectionDecideRequest
     */
    option?: string;
}

/**
 * Check if a given object implements the CollectionDecideRequest interface.
 */
export function instanceOfCollectionDecideRequest(value: object): value is CollectionDecideRequest {
    return true;
}

export function CollectionDecideRequestFromJSON(json: any): CollectionDecideRequest {
    return CollectionDecideRequestFromJSONTyped(json, false);
}

export function CollectionDecideRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionDecideRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'option': json['option'] == null ? undefined : json['option'],
    };
}

export function CollectionDecideRequestToJSON(json: any): CollectionDecideRequest {
    return CollectionDecideRequestToJSONTyped(json, false);
}

export function CollectionDecideRequestToJSONTyped(value?: CollectionDecideRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'option': value['option'],
    };
}

