/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * decision_not_valid_response_body result type (default view)
 * @export
 * @interface CollectionDecisionNotValidResponseBody
 */
export interface CollectionDecisionNotValidResponseBody {
    /**
     * Is the error a server-side fault?
     * @type {boolean}
     * @memberof CollectionDecisionNotValidResponseBody
     */
    fault: boolean;
    /**
     * ID is a unique identifier for this particular occurrence of the problem.
     * @type {string}
     * @memberof CollectionDecisionNotValidResponseBody
     */
    id: string;
    /**
     * Message is a human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof CollectionDecisionNotValidResponseBody
     */
    message: string;
    /**
     * Name is the name of this class of errors.
     * @type {string}
     * @memberof CollectionDecisionNotValidResponseBody
     */
    name: string;
    /**
     * Is the error temporary?
     * @type {boolean}
     * @memberof CollectionDecisionNotValidResponseBody
     */
    temporary: boolean;
    /**
     * Is the error a timeout?
     * @type {boolean}
     * @memberof CollectionDecisionNotValidResponseBody
     */
    timeout: boolean;
}

export function CollectionDecisionNotValidResponseBodyFromJSON(json: any): CollectionDecisionNotValidResponseBody {
    return CollectionDecisionNotValidResponseBodyFromJSONTyped(json, false);
}

export function CollectionDecisionNotValidResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionDecisionNotValidResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fault': json['fault'],
        'id': json['id'],
        'message': json['message'],
        'name': json['name'],
        'temporary': json['temporary'],
        'timeout': json['timeout'],
    };
}

export function CollectionDecisionNotValidResponseBodyToJSON(value?: CollectionDecisionNotValidResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fault': value.fault,
        'id': value.id,
        'message': value.message,
        'name': value.name,
        'temporary': value.temporary,
        'timeout': value.timeout,
    };
}


