/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * DetailedStoredCollection describes a collection retrieved by the service detail view.
 * @export
 * @interface EnduroDetailedStoredCollection
 */
export interface EnduroDetailedStoredCollection {
    /**
     * Identifier of Archivematica AIP
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    aipId?: string;
    /**
     * Datetime when the primary AIP was confirmed in storage
     * @type {Date}
     * @memberof EnduroDetailedStoredCollection
     */
    aipStoredAt?: Date;
    /**
     * Completion datetime
     * @type {Date}
     * @memberof EnduroDetailedStoredCollection
     */
    completedAt?: Date;
    /**
     * Creation datetime
     * @type {Date}
     * @memberof EnduroDetailedStoredCollection
     */
    createdAt: Date;
    /**
     * Identifier of collection
     * @type {number}
     * @memberof EnduroDetailedStoredCollection
     */
    id: number;
    /**
     * Name of the collection
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    name?: string;
    /**
     * Identifier provided by the client
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    originalId?: string;
    /**
     * Identifier of Archivematica pipeline
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    pipelineId?: string;
    /**
     * Datetime when storage was last reconciled
     * @type {Date}
     * @memberof EnduroDetailedStoredCollection
     */
    reconciliationCheckedAt?: Date;
    /**
     * Last storage reconciliation error
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    reconciliationError?: string;
    /**
     * Latest storage reconciliation status
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    reconciliationStatus?: EnduroDetailedStoredCollectionReconciliationStatusEnum;
    /**
     * Identifier of latest processing workflow run
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    runId?: string;
    /**
     * Start datetime
     * @type {Date}
     * @memberof EnduroDetailedStoredCollection
     */
    startedAt?: Date;
    /**
     * Status of the collection
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    status: EnduroDetailedStoredCollectionStatusEnum;
    /**
     * Identifier of Archivematica tranfser
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    transferId?: string;
    /**
     * Identifier of processing workflow
     * @type {string}
     * @memberof EnduroDetailedStoredCollection
     */
    workflowId?: string;
}


/**
 * @export
 */
export const EnduroDetailedStoredCollectionReconciliationStatusEnum = {
    Pending: 'pending',
    Partial: 'partial',
    Complete: 'complete',
    Unknown: 'unknown'
} as const;
export type EnduroDetailedStoredCollectionReconciliationStatusEnum = typeof EnduroDetailedStoredCollectionReconciliationStatusEnum[keyof typeof EnduroDetailedStoredCollectionReconciliationStatusEnum];

/**
 * @export
 */
export const EnduroDetailedStoredCollectionStatusEnum = {
    New: 'new',
    InProgress: 'in progress',
    Done: 'done',
    Error: 'error',
    Unknown: 'unknown',
    Queued: 'queued',
    Pending: 'pending',
    Abandoned: 'abandoned'
} as const;
export type EnduroDetailedStoredCollectionStatusEnum = typeof EnduroDetailedStoredCollectionStatusEnum[keyof typeof EnduroDetailedStoredCollectionStatusEnum];


/**
 * Check if a given object implements the EnduroDetailedStoredCollection interface.
 */
export function instanceOfEnduroDetailedStoredCollection(value: object): value is EnduroDetailedStoredCollection {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function EnduroDetailedStoredCollectionFromJSON(json: any): EnduroDetailedStoredCollection {
    return EnduroDetailedStoredCollectionFromJSONTyped(json, false);
}

export function EnduroDetailedStoredCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroDetailedStoredCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'aipId': json['aip_id'] == null ? undefined : json['aip_id'],
        'aipStoredAt': json['aip_stored_at'] == null ? undefined : (new Date(json['aip_stored_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'originalId': json['original_id'] == null ? undefined : json['original_id'],
        'pipelineId': json['pipeline_id'] == null ? undefined : json['pipeline_id'],
        'reconciliationCheckedAt': json['reconciliation_checked_at'] == null ? undefined : (new Date(json['reconciliation_checked_at'])),
        'reconciliationError': json['reconciliation_error'] == null ? undefined : json['reconciliation_error'],
        'reconciliationStatus': json['reconciliation_status'] == null ? undefined : json['reconciliation_status'],
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'status': json['status'],
        'transferId': json['transfer_id'] == null ? undefined : json['transfer_id'],
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
    };
}

export function EnduroDetailedStoredCollectionToJSON(json: any): EnduroDetailedStoredCollection {
    return EnduroDetailedStoredCollectionToJSONTyped(json, false);
}

export function EnduroDetailedStoredCollectionToJSONTyped(value?: EnduroDetailedStoredCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aip_id': value['aipId'],
        'aip_stored_at': value['aipStoredAt'] == null ? value['aipStoredAt'] : value['aipStoredAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'name': value['name'],
        'original_id': value['originalId'],
        'pipeline_id': value['pipelineId'],
        'reconciliation_checked_at': value['reconciliationCheckedAt'] == null ? value['reconciliationCheckedAt'] : value['reconciliationCheckedAt'].toISOString(),
        'reconciliation_error': value['reconciliationError'],
        'reconciliation_status': value['reconciliationStatus'],
        'run_id': value['runId'],
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'status': value['status'],
        'transfer_id': value['transferId'],
        'workflow_id': value['workflowId'],
    };
}

