/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * StoredPipeline describes a pipeline retrieved by this service.
 * @export
 * @interface EnduroStoredPipeline
 */
export interface EnduroStoredPipeline {
    /**
     * Maximum concurrent transfers
     * @type {number}
     * @memberof EnduroStoredPipeline
     */
    capacity?: number;
    /**
     * Current transfers
     * @type {number}
     * @memberof EnduroStoredPipeline
     */
    current?: number;
    /**
     * Identifier of pipeline
     * @type {string}
     * @memberof EnduroStoredPipeline
     */
    id?: string;
    /**
     * Name of the pipeline
     * @type {string}
     * @memberof EnduroStoredPipeline
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EnduroStoredPipeline
     */
    status?: string;
}

/**
 * Check if a given object implements the EnduroStoredPipeline interface.
 */
export function instanceOfEnduroStoredPipeline(value: object): value is EnduroStoredPipeline {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function EnduroStoredPipelineFromJSON(json: any): EnduroStoredPipeline {
    return EnduroStoredPipelineFromJSONTyped(json, false);
}

export function EnduroStoredPipelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroStoredPipeline {
    if (json == null) {
        return json;
    }
    return {
        
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'current': json['current'] == null ? undefined : json['current'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function EnduroStoredPipelineToJSON(json: any): EnduroStoredPipeline {
    return EnduroStoredPipelineToJSONTyped(json, false);
}

export function EnduroStoredPipelineToJSONTyped(value?: EnduroStoredPipeline | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capacity': value['capacity'],
        'current': value['current'],
        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
    };
}

