/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EnduroCollectionWorkflowHistory } from './EnduroCollectionWorkflowHistory';
import {
    EnduroCollectionWorkflowHistoryFromJSON,
    EnduroCollectionWorkflowHistoryFromJSONTyped,
    EnduroCollectionWorkflowHistoryToJSON,
} from './EnduroCollectionWorkflowHistory';

/**
 * 
 * @export
 * @interface EnduroCollectionWorkflowStatus
 */
export interface EnduroCollectionWorkflowStatus {
    /**
     * 
     * @type {Array<EnduroCollectionWorkflowHistory>}
     * @memberof EnduroCollectionWorkflowStatus
     */
    history?: Array<EnduroCollectionWorkflowHistory>;
    /**
     * 
     * @type {string}
     * @memberof EnduroCollectionWorkflowStatus
     */
    status?: string;
}

/**
 * Check if a given object implements the EnduroCollectionWorkflowStatus interface.
 */
export function instanceOfEnduroCollectionWorkflowStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EnduroCollectionWorkflowStatusFromJSON(json: any): EnduroCollectionWorkflowStatus {
    return EnduroCollectionWorkflowStatusFromJSONTyped(json, false);
}

export function EnduroCollectionWorkflowStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroCollectionWorkflowStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'history': !exists(json, 'history') ? undefined : ((json['history'] as Array<any>).map(EnduroCollectionWorkflowHistoryFromJSON)),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function EnduroCollectionWorkflowStatusToJSON(value?: EnduroCollectionWorkflowStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'history': value.history === undefined ? undefined : ((value.history as Array<any>).map(EnduroCollectionWorkflowHistoryToJSON)),
        'status': value.status,
    };
}

