/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * StoredPipeline describes a pipeline retrieved by this service.
 * @export
 * @interface EnduroStoredPipeline
 */
export interface EnduroStoredPipeline {
    /**
     * Maximum concurrent transfers
     * @type {number}
     * @memberof EnduroStoredPipeline
     */
    capacity?: number;
    /**
     * Current transfers
     * @type {number}
     * @memberof EnduroStoredPipeline
     */
    current?: number;
    /**
     * Identifier of pipeline
     * @type {string}
     * @memberof EnduroStoredPipeline
     */
    id?: string;
    /**
     * Name of the pipeline
     * @type {string}
     * @memberof EnduroStoredPipeline
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EnduroStoredPipeline
     */
    status?: string;
}

/**
 * Check if a given object implements the EnduroStoredPipeline interface.
 */
export function instanceOfEnduroStoredPipeline(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function EnduroStoredPipelineFromJSON(json: any): EnduroStoredPipeline {
    return EnduroStoredPipelineFromJSONTyped(json, false);
}

export function EnduroStoredPipelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroStoredPipeline {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capacity': !exists(json, 'capacity') ? undefined : json['capacity'],
        'current': !exists(json, 'current') ? undefined : json['current'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function EnduroStoredPipelineToJSON(value?: EnduroStoredPipeline | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capacity': value.capacity,
        'current': value.current,
        'id': value.id,
        'name': value.name,
        'status': value.status,
    };
}

