/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * StoredCollection describes a collection retrieved by the service.
 * @export
 * @interface EnduroStoredCollection
 */
export interface EnduroStoredCollection {
    /**
     * Identifier of Archivematica AIP
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    aipId?: string;
    /**
     * Completion datetime
     * @type {Date}
     * @memberof EnduroStoredCollection
     */
    completedAt?: Date;
    /**
     * Creation datetime
     * @type {Date}
     * @memberof EnduroStoredCollection
     */
    createdAt: Date;
    /**
     * Identifier of collection
     * @type {number}
     * @memberof EnduroStoredCollection
     */
    id: number;
    /**
     * Name of the collection
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    name?: string;
    /**
     * Identifier provided by the client
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    originalId?: string;
    /**
     * Identifier of Archivematica pipeline
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    pipelineId?: string;
    /**
     * Identifier of latest processing workflow run
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    runId?: string;
    /**
     * Start datetime
     * @type {Date}
     * @memberof EnduroStoredCollection
     */
    startedAt?: Date;
    /**
     * Status of the collection
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    status: EnduroStoredCollectionStatusEnum;
    /**
     * Identifier of Archivematica tranfser
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    transferId?: string;
    /**
     * Identifier of processing workflow
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    workflowId?: string;
}


/**
 * @export
 */
export const EnduroStoredCollectionStatusEnum = {
    New: 'new',
    InProgress: 'in progress',
    Done: 'done',
    Error: 'error',
    Unknown: 'unknown',
    Queued: 'queued',
    Pending: 'pending',
    Abandoned: 'abandoned'
} as const;
export type EnduroStoredCollectionStatusEnum = typeof EnduroStoredCollectionStatusEnum[keyof typeof EnduroStoredCollectionStatusEnum];


/**
 * Check if a given object implements the EnduroStoredCollection interface.
 */
export function instanceOfEnduroStoredCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function EnduroStoredCollectionFromJSON(json: any): EnduroStoredCollection {
    return EnduroStoredCollectionFromJSONTyped(json, false);
}

export function EnduroStoredCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroStoredCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aipId': !exists(json, 'aip_id') ? undefined : json['aip_id'],
        'completedAt': !exists(json, 'completed_at') ? undefined : (new Date(json['completed_at'])),
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'originalId': !exists(json, 'original_id') ? undefined : json['original_id'],
        'pipelineId': !exists(json, 'pipeline_id') ? undefined : json['pipeline_id'],
        'runId': !exists(json, 'run_id') ? undefined : json['run_id'],
        'startedAt': !exists(json, 'started_at') ? undefined : (new Date(json['started_at'])),
        'status': json['status'],
        'transferId': !exists(json, 'transfer_id') ? undefined : json['transfer_id'],
        'workflowId': !exists(json, 'workflow_id') ? undefined : json['workflow_id'],
    };
}

export function EnduroStoredCollectionToJSON(value?: EnduroStoredCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aip_id': value.aipId,
        'completed_at': value.completedAt === undefined ? undefined : (value.completedAt.toISOString()),
        'created_at': (value.createdAt.toISOString()),
        'id': value.id,
        'name': value.name,
        'original_id': value.originalId,
        'pipeline_id': value.pipelineId,
        'run_id': value.runId,
        'started_at': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'status': value.status,
        'transfer_id': value.transferId,
        'workflow_id': value.workflowId,
    };
}

