/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnduroStoredCollection } from './EnduroStoredCollection';
import {
    EnduroStoredCollectionFromJSON,
    EnduroStoredCollectionFromJSONTyped,
    EnduroStoredCollectionToJSON,
    EnduroStoredCollectionToJSONTyped,
} from './EnduroStoredCollection';

/**
 * 
 * @export
 * @interface EnduroMonitorUpdate
 */
export interface EnduroMonitorUpdate {
    /**
     * Identifier of collection
     * @type {number}
     * @memberof EnduroMonitorUpdate
     */
    id: number;
    /**
     * 
     * @type {EnduroStoredCollection}
     * @memberof EnduroMonitorUpdate
     */
    item?: EnduroStoredCollection;
    /**
     * Type of the event
     * @type {string}
     * @memberof EnduroMonitorUpdate
     */
    type: string;
}

/**
 * Check if a given object implements the EnduroMonitorUpdate interface.
 */
export function instanceOfEnduroMonitorUpdate(value: object): value is EnduroMonitorUpdate {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EnduroMonitorUpdateFromJSON(json: any): EnduroMonitorUpdate {
    return EnduroMonitorUpdateFromJSONTyped(json, false);
}

export function EnduroMonitorUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroMonitorUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'item': json['item'] == null ? undefined : EnduroStoredCollectionFromJSON(json['item']),
        'type': json['type'],
    };
}

export function EnduroMonitorUpdateToJSON(json: any): EnduroMonitorUpdate {
    return EnduroMonitorUpdateToJSONTyped(json, false);
}

export function EnduroMonitorUpdateToJSONTyped(value?: EnduroMonitorUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'item': EnduroStoredCollectionToJSON(value['item']),
        'type': value['type'],
    };
}

