/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnduroCollectionWorkflowHistory } from './EnduroCollectionWorkflowHistory';
import {
    EnduroCollectionWorkflowHistoryFromJSON,
    EnduroCollectionWorkflowHistoryFromJSONTyped,
    EnduroCollectionWorkflowHistoryToJSON,
    EnduroCollectionWorkflowHistoryToJSONTyped,
} from './EnduroCollectionWorkflowHistory';

/**
 * WorkflowStatus describes the processing workflow status of a collection.
 * @export
 * @interface EnduroCollectionWorkflowStatus
 */
export interface EnduroCollectionWorkflowStatus {
    /**
     * 
     * @type {Array<EnduroCollectionWorkflowHistory>}
     * @memberof EnduroCollectionWorkflowStatus
     */
    history?: Array<EnduroCollectionWorkflowHistory>;
    /**
     * 
     * @type {string}
     * @memberof EnduroCollectionWorkflowStatus
     */
    status?: string;
}

/**
 * Check if a given object implements the EnduroCollectionWorkflowStatus interface.
 */
export function instanceOfEnduroCollectionWorkflowStatus(value: object): value is EnduroCollectionWorkflowStatus {
    return true;
}

export function EnduroCollectionWorkflowStatusFromJSON(json: any): EnduroCollectionWorkflowStatus {
    return EnduroCollectionWorkflowStatusFromJSONTyped(json, false);
}

export function EnduroCollectionWorkflowStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroCollectionWorkflowStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'history': json['history'] == null ? undefined : ((json['history'] as Array<any>).map(EnduroCollectionWorkflowHistoryFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function EnduroCollectionWorkflowStatusToJSON(json: any): EnduroCollectionWorkflowStatus {
    return EnduroCollectionWorkflowStatusToJSONTyped(json, false);
}

export function EnduroCollectionWorkflowStatusToJSONTyped(value?: EnduroCollectionWorkflowStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'history': value['history'] == null ? undefined : ((value['history'] as Array<any>).map(EnduroCollectionWorkflowHistoryToJSON)),
        'status': value['status'],
    };
}

