/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * StoredPipeline describes a pipeline retrieved by this service. (default view)
 * @export
 * @interface EnduroStoredPipelineResponse
 */
export interface EnduroStoredPipelineResponse {
    /**
     * Maximum concurrent transfers
     * @type {number}
     * @memberof EnduroStoredPipelineResponse
     */
    capacity?: number;
    /**
     * Current transfers
     * @type {number}
     * @memberof EnduroStoredPipelineResponse
     */
    current?: number;
    /**
     * Identifier of the pipeline
     * @type {string}
     * @memberof EnduroStoredPipelineResponse
     */
    id?: string;
    /**
     * Name of the pipeline
     * @type {string}
     * @memberof EnduroStoredPipelineResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EnduroStoredPipelineResponse
     */
    status?: string;
}

export function EnduroStoredPipelineResponseFromJSON(json: any): EnduroStoredPipelineResponse {
    return EnduroStoredPipelineResponseFromJSONTyped(json, false);
}

export function EnduroStoredPipelineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroStoredPipelineResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capacity': !exists(json, 'capacity') ? undefined : json['capacity'],
        'current': !exists(json, 'current') ? undefined : json['current'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function EnduroStoredPipelineResponseToJSON(value?: EnduroStoredPipelineResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capacity': value.capacity,
        'current': value.current,
        'id': value.id,
        'name': value.name,
        'status': value.status,
    };
}


