/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * StatusTransition describes a committed collection status change.
 * @export
 * @interface EnduroCollectionStatusTransition
 */
export interface EnduroCollectionStatusTransition {
    /**
     * Identifier of the status transition
     * @type {number}
     * @memberof EnduroCollectionStatusTransition
     */
    id: number;
    /**
     * Whether the transition starts a fully recorded workflow run
     * @type {boolean}
     * @memberof EnduroCollectionStatusTransition
     */
    isRunStart: boolean;
    /**
     * Transition datetime
     * @type {Date}
     * @memberof EnduroCollectionStatusTransition
     */
    occurredAt: Date;
    /**
     * Status before the transition
     * @type {EnduroCollectionStatusTransitionPreviousStatusEnum}
     * @memberof EnduroCollectionStatusTransition
     */
    previousStatus?: EnduroCollectionStatusTransitionPreviousStatusEnum;
    /**
     * Machine-readable reason for the transition
     * @type {string}
     * @memberof EnduroCollectionStatusTransition
     */
    reason?: string;
    /**
     * Identifier of the processing workflow run
     * @type {string}
     * @memberof EnduroCollectionStatusTransition
     */
    runId: string;
    /**
     * Status entered by the transition
     * @type {EnduroCollectionStatusTransitionStatusEnum}
     * @memberof EnduroCollectionStatusTransition
     */
    status: EnduroCollectionStatusTransitionStatusEnum;
    /**
     * Identifier of the processing workflow
     * @type {string}
     * @memberof EnduroCollectionStatusTransition
     */
    workflowId: string;
}


/**
 * @export
 */
export const EnduroCollectionStatusTransitionPreviousStatusEnum = {
    New: 'new',
    InProgress: 'in progress',
    Done: 'done',
    Error: 'error',
    Unknown: 'unknown',
    Queued: 'queued',
    Pending: 'pending',
    Abandoned: 'abandoned'
} as const;
export type EnduroCollectionStatusTransitionPreviousStatusEnum = typeof EnduroCollectionStatusTransitionPreviousStatusEnum[keyof typeof EnduroCollectionStatusTransitionPreviousStatusEnum];

/**
 * @export
 */
export const EnduroCollectionStatusTransitionStatusEnum = {
    New: 'new',
    InProgress: 'in progress',
    Done: 'done',
    Error: 'error',
    Unknown: 'unknown',
    Queued: 'queued',
    Pending: 'pending',
    Abandoned: 'abandoned'
} as const;
export type EnduroCollectionStatusTransitionStatusEnum = typeof EnduroCollectionStatusTransitionStatusEnum[keyof typeof EnduroCollectionStatusTransitionStatusEnum];


/**
 * Check if a given object implements the EnduroCollectionStatusTransition interface.
 */
export function instanceOfEnduroCollectionStatusTransition(value: object): value is EnduroCollectionStatusTransition {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('isRunStart' in (value as Record<string, any>)) && !('is_run_start' in (value as Record<string, any>))) || ((value as Record<string, any>)['isRunStart'] === undefined && (value as Record<string, any>)['is_run_start'] === undefined)) return false;
    if ((!('occurredAt' in (value as Record<string, any>)) && !('occurred_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['occurredAt'] === undefined && (value as Record<string, any>)['occurred_at'] === undefined)) return false;
    if ((!('runId' in (value as Record<string, any>)) && !('run_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['runId'] === undefined && (value as Record<string, any>)['run_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('workflowId' in (value as Record<string, any>)) && !('workflow_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['workflowId'] === undefined && (value as Record<string, any>)['workflow_id'] === undefined)) return false;
    return true;
}

export function EnduroCollectionStatusTransitionFromJSON(json: any): EnduroCollectionStatusTransition {
    return EnduroCollectionStatusTransitionFromJSONTyped(json, false);
}

export function EnduroCollectionStatusTransitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroCollectionStatusTransition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'isRunStart': json['is_run_start'],
        'occurredAt': (new Date(json['occurred_at'])),
        'previousStatus': json['previous_status'] == null ? undefined : json['previous_status'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'runId': json['run_id'],
        'status': json['status'],
        'workflowId': json['workflow_id'],
    };
}

export function EnduroCollectionStatusTransitionToJSON(json: any): EnduroCollectionStatusTransition {
    return EnduroCollectionStatusTransitionToJSONTyped(json, false);
}

export function EnduroCollectionStatusTransitionToJSONTyped(value?: EnduroCollectionStatusTransition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'is_run_start': value['isRunStart'],
        'occurred_at': value['occurredAt'].toISOString(),
        'previous_status': value['previousStatus'],
        'reason': value['reason'],
        'run_id': value['runId'],
        'status': value['status'],
        'workflow_id': value['workflowId'],
    };
}

