/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pipeline describes an Archivematica pipeline.
 * @export
 * @interface Pipeline
 */
export interface Pipeline {
    /**
     * Maximum concurrent transfers
     * @type {number}
     * @memberof Pipeline
     */
    capacity?: number;
    /**
     * Current transfers
     * @type {number}
     * @memberof Pipeline
     */
    current?: number;
    /**
     * Identifier of pipeline
     * @type {string}
     * @memberof Pipeline
     */
    id?: string;
    /**
     * Name of the pipeline
     * @type {string}
     * @memberof Pipeline
     */
    name: string;
}

/**
 * Check if a given object implements the Pipeline interface.
 */
export function instanceOfPipeline(value: object): value is Pipeline {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PipelineFromJSON(json: any): Pipeline {
    return PipelineFromJSONTyped(json, false);
}

export function PipelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pipeline {
    if (json == null) {
        return json;
    }
    return {
        
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'current': json['current'] == null ? undefined : json['current'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
    };
}

export function PipelineToJSON(json: any): Pipeline {
    return PipelineToJSONTyped(json, false);
}

export function PipelineToJSONTyped(value?: Pipeline | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capacity': value['capacity'],
        'current': value['current'],
        'id': value['id'],
        'name': value['name'],
    };
}

