/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ShowResponseBody result type (default view)
 * @export
 * @interface PipelineShowResponseBody
 */
export interface PipelineShowResponseBody {
    /**
     * Maximum concurrent transfers
     * @type {number}
     * @memberof PipelineShowResponseBody
     */
    capacity?: number;
    /**
     * Current transfers
     * @type {number}
     * @memberof PipelineShowResponseBody
     */
    current?: number;
    /**
     * Name of the collection
     * @type {string}
     * @memberof PipelineShowResponseBody
     */
    id?: string;
    /**
     * Name of the collection
     * @type {string}
     * @memberof PipelineShowResponseBody
     */
    name: string;
}

export function PipelineShowResponseBodyFromJSON(json: any): PipelineShowResponseBody {
    return PipelineShowResponseBodyFromJSONTyped(json, false);
}

export function PipelineShowResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineShowResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capacity': !exists(json, 'capacity') ? undefined : json['capacity'],
        'current': !exists(json, 'current') ? undefined : json['current'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
    };
}

export function PipelineShowResponseBodyToJSON(value?: PipelineShowResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capacity': value.capacity,
        'current': value.current,
        'id': value.id,
        'name': value.name,
    };
}


