/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * RetryResult describes how retry processing was restarted.
 * @export
 * @interface RetryResult
 */
export interface RetryResult {
    /**
     * Selected retry mode
     * @type {string}
     * @memberof RetryResult
     */
    mode: RetryResultModeEnum;
}


/**
 * @export
 */
export const RetryResultModeEnum = {
    FullReprocess: 'full_reprocess',
    ReconcileExistingAip: 'reconcile_existing_aip'
} as const;
export type RetryResultModeEnum = typeof RetryResultModeEnum[keyof typeof RetryResultModeEnum];


/**
 * Check if a given object implements the RetryResult interface.
 */
export function instanceOfRetryResult(value: object): value is RetryResult {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function RetryResultFromJSON(json: any): RetryResult {
    return RetryResultFromJSONTyped(json, false);
}

export function RetryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetryResult {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
    };
}

export function RetryResultToJSON(json: any): RetryResult {
    return RetryResultToJSONTyped(json, false);
}

export function RetryResultToJSONTyped(value?: RetryResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
    };
}

