/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitRequestBody
 */
export interface SubmitRequestBody {
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestBody
     */
    completedDir?: string;
    /**
     * 
     * @type {number}
     * @memberof SubmitRequestBody
     */
    depth?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SubmitRequestBody
     */
    excludeHiddenFiles?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestBody
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestBody
     */
    pipeline?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubmitRequestBody
     */
    processNameMetadata?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestBody
     */
    processingConfig?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubmitRequestBody
     */
    rejectDuplicates?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestBody
     */
    retentionPeriod?: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitRequestBody
     */
    transferType?: string;
}

/**
 * Check if a given object implements the SubmitRequestBody interface.
 */
export function instanceOfSubmitRequestBody(value: object): value is SubmitRequestBody {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function SubmitRequestBodyFromJSON(json: any): SubmitRequestBody {
    return SubmitRequestBodyFromJSONTyped(json, false);
}

export function SubmitRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'completedDir': json['completed_dir'] == null ? undefined : json['completed_dir'],
        'depth': json['depth'] == null ? undefined : json['depth'],
        'excludeHiddenFiles': json['exclude_hidden_files'] == null ? undefined : json['exclude_hidden_files'],
        'path': json['path'],
        'pipeline': json['pipeline'] == null ? undefined : json['pipeline'],
        'processNameMetadata': json['process_name_metadata'] == null ? undefined : json['process_name_metadata'],
        'processingConfig': json['processing_config'] == null ? undefined : json['processing_config'],
        'rejectDuplicates': json['reject_duplicates'] == null ? undefined : json['reject_duplicates'],
        'retentionPeriod': json['retention_period'] == null ? undefined : json['retention_period'],
        'transferType': json['transfer_type'] == null ? undefined : json['transfer_type'],
    };
}

export function SubmitRequestBodyToJSON(json: any): SubmitRequestBody {
    return SubmitRequestBodyToJSONTyped(json, false);
}

export function SubmitRequestBodyToJSONTyped(value?: SubmitRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed_dir': value['completedDir'],
        'depth': value['depth'],
        'exclude_hidden_files': value['excludeHiddenFiles'],
        'path': value['path'],
        'pipeline': value['pipeline'],
        'process_name_metadata': value['processNameMetadata'],
        'processing_config': value['processingConfig'],
        'reject_duplicates': value['rejectDuplicates'],
        'retention_period': value['retentionPeriod'],
        'transfer_type': value['transferType'],
    };
}

