/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * SwaggerApi - interface
 * 
 * @export
 * @interface SwaggerApiInterface
 */
export interface SwaggerApiInterface {
    /**
     * JSON document containing the API swagger definition.
     * @summary Download internal/api/gen/http/openapi.json
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SwaggerApiInterface
     */
    swaggerSwaggerSwaggerJsonRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * JSON document containing the API swagger definition.
     * Download internal/api/gen/http/openapi.json
     */
    swaggerSwaggerSwaggerJson(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Blob>;

}

/**
 * 
 */
export class SwaggerApi extends runtime.BaseAPI implements SwaggerApiInterface {

    /**
     * JSON document containing the API swagger definition.
     * Download internal/api/gen/http/openapi.json
     */
    async swaggerSwaggerSwaggerJsonRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/swagger/swagger.json`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * JSON document containing the API swagger definition.
     * Download internal/api/gen/http/openapi.json
     */
    async swaggerSwaggerSwaggerJson(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Blob> {
        const response = await this.swaggerSwaggerSwaggerJsonRaw(initOverrides);
        return await response.value();
    }

}
