// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artefactual-labs/enduro/internal/pipeline (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -typed -destination=./internal/pipeline/fake/mock_pipeline.go -package=fake github.com/artefactual-labs/enduro/internal/pipeline Service
//

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	reflect "reflect"

	pipeline "github.com/artefactual-labs/enduro/internal/api/gen/pipeline"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockService) List(arg0 context.Context, arg1 *pipeline.ListPayload) ([]*pipeline.EnduroStoredPipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*pipeline.EnduroStoredPipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(arg0, arg1 any) *MockServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), arg0, arg1)
	return &MockServiceListCall{Call: call}
}

// MockServiceListCall wrap *gomock.Call
type MockServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListCall) Return(arg0 []*pipeline.EnduroStoredPipeline, arg1 error) *MockServiceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListCall) Do(f func(context.Context, *pipeline.ListPayload) ([]*pipeline.EnduroStoredPipeline, error)) *MockServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListCall) DoAndReturn(f func(context.Context, *pipeline.ListPayload) ([]*pipeline.EnduroStoredPipeline, error)) *MockServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Processing mocks base method.
func (m *MockService) Processing(arg0 context.Context, arg1 *pipeline.ProcessingPayload) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Processing", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Processing indicates an expected call of Processing.
func (mr *MockServiceMockRecorder) Processing(arg0, arg1 any) *MockServiceProcessingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Processing", reflect.TypeOf((*MockService)(nil).Processing), arg0, arg1)
	return &MockServiceProcessingCall{Call: call}
}

// MockServiceProcessingCall wrap *gomock.Call
type MockServiceProcessingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceProcessingCall) Return(arg0 []string, arg1 error) *MockServiceProcessingCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceProcessingCall) Do(f func(context.Context, *pipeline.ProcessingPayload) ([]string, error)) *MockServiceProcessingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceProcessingCall) DoAndReturn(f func(context.Context, *pipeline.ProcessingPayload) ([]string, error)) *MockServiceProcessingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Show mocks base method.
func (m *MockService) Show(arg0 context.Context, arg1 *pipeline.ShowPayload) (*pipeline.EnduroStoredPipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Show", arg0, arg1)
	ret0, _ := ret[0].(*pipeline.EnduroStoredPipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Show indicates an expected call of Show.
func (mr *MockServiceMockRecorder) Show(arg0, arg1 any) *MockServiceShowCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockService)(nil).Show), arg0, arg1)
	return &MockServiceShowCall{Call: call}
}

// MockServiceShowCall wrap *gomock.Call
type MockServiceShowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceShowCall) Return(arg0 *pipeline.EnduroStoredPipeline, arg1 error) *MockServiceShowCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceShowCall) Do(f func(context.Context, *pipeline.ShowPayload) (*pipeline.EnduroStoredPipeline, error)) *MockServiceShowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceShowCall) DoAndReturn(f func(context.Context, *pipeline.ShowPayload) (*pipeline.EnduroStoredPipeline, error)) *MockServiceShowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
