/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * StoredCollection describes a collection retrieved by the service.
 * @export
 * @interface EnduroStoredCollection
 */
export interface EnduroStoredCollection {
    /**
     * Identifier of Archivematica AIP
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    aipId?: string;
    /**
     * Completion datetime
     * @type {Date}
     * @memberof EnduroStoredCollection
     */
    completedAt?: Date;
    /**
     * Creation datetime
     * @type {Date}
     * @memberof EnduroStoredCollection
     */
    createdAt: Date;
    /**
     * Identifier of collection
     * @type {number}
     * @memberof EnduroStoredCollection
     */
    id: number;
    /**
     * Name of the collection
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    name?: string;
    /**
     * Identifier provided by the client
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    originalId?: string;
    /**
     * Identifier of Archivematica pipeline
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    pipelineId?: string;
    /**
     * Identifier of latest processing workflow run
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    runId?: string;
    /**
     * Start datetime
     * @type {Date}
     * @memberof EnduroStoredCollection
     */
    startedAt?: Date;
    /**
     * Status of the collection
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    status: EnduroStoredCollectionStatusEnum;
    /**
     * Identifier of Archivematica tranfser
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    transferId?: string;
    /**
     * Identifier of processing workflow
     * @type {string}
     * @memberof EnduroStoredCollection
     */
    workflowId?: string;
}

/**
* @export
* @enum {string}
*/
export enum EnduroStoredCollectionStatusEnum {
    New = 'new',
    InProgress = 'in progress',
    Done = 'done',
    Error = 'error',
    Unknown = 'unknown',
    Queued = 'queued',
    Pending = 'pending',
    Abandoned = 'abandoned',
    UnknownDefaultOpenApi = '11184809'
}


/**
 * Check if a given object implements the EnduroStoredCollection interface.
 */
export function instanceOfEnduroStoredCollection(value: object): value is EnduroStoredCollection {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function EnduroStoredCollectionFromJSON(json: any): EnduroStoredCollection {
    return EnduroStoredCollectionFromJSONTyped(json, false);
}

export function EnduroStoredCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroStoredCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'aipId': json['aip_id'] == null ? undefined : json['aip_id'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'originalId': json['original_id'] == null ? undefined : json['original_id'],
        'pipelineId': json['pipeline_id'] == null ? undefined : json['pipeline_id'],
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'status': json['status'],
        'transferId': json['transfer_id'] == null ? undefined : json['transfer_id'],
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
    };
}

export function EnduroStoredCollectionToJSON(json: any): EnduroStoredCollection {
    return EnduroStoredCollectionToJSONTyped(json, false);
}

export function EnduroStoredCollectionToJSONTyped(value?: EnduroStoredCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aip_id': value['aipId'],
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'name': value['name'],
        'original_id': value['originalId'],
        'pipeline_id': value['pipelineId'],
        'run_id': value['runId'],
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'status': value['status'],
        'transfer_id': value['transferId'],
        'workflow_id': value['workflowId'],
    };
}

