/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pipeline not found.
 * @export
 * @interface PipelineNotFound
 */
export interface PipelineNotFound {
    /**
     * Identifier of missing pipeline
     * @type {string}
     * @memberof PipelineNotFound
     */
    id: string;
    /**
     * Message of error
     * @type {string}
     * @memberof PipelineNotFound
     */
    message: string;
}

/**
 * Check if a given object implements the PipelineNotFound interface.
 */
export function instanceOfPipelineNotFound(value: object): value is PipelineNotFound {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PipelineNotFoundFromJSON(json: any): PipelineNotFound {
    return PipelineNotFoundFromJSONTyped(json, false);
}

export function PipelineNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineNotFound {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
    };
}

export function PipelineNotFoundToJSON(json: any): PipelineNotFound {
    return PipelineNotFoundToJSONTyped(json, false);
}

export function PipelineNotFoundToJSONTyped(value?: PipelineNotFound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'message': value['message'],
    };
}

