// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/collection/bulk_workflow.go
//
// Generated by this command:
//
//	mockgen -typed -source=./internal/collection/bulk_workflow.go -destination=./internal/collection/mock_bulk_collection_service_test.go -package=collection -mock_names=bulkCollectionService=MockBulkCollectionService
//

// Package collection is a generated GoMock package.
package collection

import (
	context "context"
	reflect "reflect"

	collection "github.com/artefactual-labs/enduro/internal/api/gen/collection"
	gomock "go.uber.org/mock/gomock"
)

// MockBulkCollectionService is a mock of bulkCollectionService interface.
type MockBulkCollectionService struct {
	ctrl     *gomock.Controller
	recorder *MockBulkCollectionServiceMockRecorder
	isgomock struct{}
}

// MockBulkCollectionServiceMockRecorder is the mock recorder for MockBulkCollectionService.
type MockBulkCollectionServiceMockRecorder struct {
	mock *MockBulkCollectionService
}

// NewMockBulkCollectionService creates a new mock instance.
func NewMockBulkCollectionService(ctrl *gomock.Controller) *MockBulkCollectionService {
	mock := &MockBulkCollectionService{ctrl: ctrl}
	mock.recorder = &MockBulkCollectionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkCollectionService) EXPECT() *MockBulkCollectionServiceMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockBulkCollectionService) Cancel(arg0 context.Context, arg1 *collection.CancelPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockBulkCollectionServiceMockRecorder) Cancel(arg0, arg1 any) *MockBulkCollectionServiceCancelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockBulkCollectionService)(nil).Cancel), arg0, arg1)
	return &MockBulkCollectionServiceCancelCall{Call: call}
}

// MockBulkCollectionServiceCancelCall wrap *gomock.Call
type MockBulkCollectionServiceCancelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBulkCollectionServiceCancelCall) Return(arg0 error) *MockBulkCollectionServiceCancelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBulkCollectionServiceCancelCall) Do(f func(context.Context, *collection.CancelPayload) error) *MockBulkCollectionServiceCancelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBulkCollectionServiceCancelCall) DoAndReturn(f func(context.Context, *collection.CancelPayload) error) *MockBulkCollectionServiceCancelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Decide mocks base method.
func (m *MockBulkCollectionService) Decide(arg0 context.Context, arg1 *collection.DecidePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decide", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decide indicates an expected call of Decide.
func (mr *MockBulkCollectionServiceMockRecorder) Decide(arg0, arg1 any) *MockBulkCollectionServiceDecideCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decide", reflect.TypeOf((*MockBulkCollectionService)(nil).Decide), arg0, arg1)
	return &MockBulkCollectionServiceDecideCall{Call: call}
}

// MockBulkCollectionServiceDecideCall wrap *gomock.Call
type MockBulkCollectionServiceDecideCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBulkCollectionServiceDecideCall) Return(arg0 error) *MockBulkCollectionServiceDecideCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBulkCollectionServiceDecideCall) Do(f func(context.Context, *collection.DecidePayload) error) *MockBulkCollectionServiceDecideCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBulkCollectionServiceDecideCall) DoAndReturn(f func(context.Context, *collection.DecidePayload) error) *MockBulkCollectionServiceDecideCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockBulkCollectionService) List(arg0 context.Context, arg1 *collection.ListPayload) (*collection.ListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*collection.ListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBulkCollectionServiceMockRecorder) List(arg0, arg1 any) *MockBulkCollectionServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBulkCollectionService)(nil).List), arg0, arg1)
	return &MockBulkCollectionServiceListCall{Call: call}
}

// MockBulkCollectionServiceListCall wrap *gomock.Call
type MockBulkCollectionServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBulkCollectionServiceListCall) Return(arg0 *collection.ListResult, arg1 error) *MockBulkCollectionServiceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBulkCollectionServiceListCall) Do(f func(context.Context, *collection.ListPayload) (*collection.ListResult, error)) *MockBulkCollectionServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBulkCollectionServiceListCall) DoAndReturn(f func(context.Context, *collection.ListPayload) (*collection.ListResult, error)) *MockBulkCollectionServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Retry mocks base method.
func (m *MockBulkCollectionService) Retry(arg0 context.Context, arg1 *collection.RetryPayload) (*collection.RetryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retry", arg0, arg1)
	ret0, _ := ret[0].(*collection.RetryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retry indicates an expected call of Retry.
func (mr *MockBulkCollectionServiceMockRecorder) Retry(arg0, arg1 any) *MockBulkCollectionServiceRetryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retry", reflect.TypeOf((*MockBulkCollectionService)(nil).Retry), arg0, arg1)
	return &MockBulkCollectionServiceRetryCall{Call: call}
}

// MockBulkCollectionServiceRetryCall wrap *gomock.Call
type MockBulkCollectionServiceRetryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBulkCollectionServiceRetryCall) Return(arg0 *collection.RetryResult, arg1 error) *MockBulkCollectionServiceRetryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBulkCollectionServiceRetryCall) Do(f func(context.Context, *collection.RetryPayload) (*collection.RetryResult, error)) *MockBulkCollectionServiceRetryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBulkCollectionServiceRetryCall) DoAndReturn(f func(context.Context, *collection.RetryPayload) (*collection.RetryResult, error)) *MockBulkCollectionServiceRetryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Show mocks base method.
func (m *MockBulkCollectionService) Show(arg0 context.Context, arg1 *collection.ShowPayload) (*collection.EnduroDetailedStoredCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Show", arg0, arg1)
	ret0, _ := ret[0].(*collection.EnduroDetailedStoredCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Show indicates an expected call of Show.
func (mr *MockBulkCollectionServiceMockRecorder) Show(arg0, arg1 any) *MockBulkCollectionServiceShowCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockBulkCollectionService)(nil).Show), arg0, arg1)
	return &MockBulkCollectionServiceShowCall{Call: call}
}

// MockBulkCollectionServiceShowCall wrap *gomock.Call
type MockBulkCollectionServiceShowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBulkCollectionServiceShowCall) Return(arg0 *collection.EnduroDetailedStoredCollection, arg1 error) *MockBulkCollectionServiceShowCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBulkCollectionServiceShowCall) Do(f func(context.Context, *collection.ShowPayload) (*collection.EnduroDetailedStoredCollection, error)) *MockBulkCollectionServiceShowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBulkCollectionServiceShowCall) DoAndReturn(f func(context.Context, *collection.ShowPayload) (*collection.EnduroDetailedStoredCollection, error)) *MockBulkCollectionServiceShowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
