apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: "opensearch"
          image: "opensearchproject/opensearch:1.3.2"
          env:
            - name: discovery.type
              value: single-node
            - name: bootstrap.memory_lock
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xmx512M -Xms512M"
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: "false"
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
          resources: {}
      volumes:
        - name: opensearch-data
          persistentVolumeClaim:
            claimName: opensearch-persistentvolumeclaim
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  ports:
    - port: 9200
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-persistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
