/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BulkRequestBody,
  BulkResult,
  BulkStatusResult,
  CollectionDecideRequest,
  CollectionNotfound,
  EnduroCollectionWorkflowStatus,
  EnduroDetailedStoredCollection,
  EnduroMonitorUpdate,
  ListResponseBody,
  RetryResult,
} from '../models/index';
import {
    BulkRequestBodyFromJSON,
    BulkRequestBodyToJSON,
    BulkResultFromJSON,
    BulkResultToJSON,
    BulkStatusResultFromJSON,
    BulkStatusResultToJSON,
    CollectionDecideRequestFromJSON,
    CollectionDecideRequestToJSON,
    CollectionNotfoundFromJSON,
    CollectionNotfoundToJSON,
    EnduroCollectionWorkflowStatusFromJSON,
    EnduroCollectionWorkflowStatusToJSON,
    EnduroDetailedStoredCollectionFromJSON,
    EnduroDetailedStoredCollectionToJSON,
    EnduroMonitorUpdateFromJSON,
    EnduroMonitorUpdateToJSON,
    ListResponseBodyFromJSON,
    ListResponseBodyToJSON,
    RetryResultFromJSON,
    RetryResultToJSON,
} from '../models/index';

export interface CollectionApiCollectionBulkRequest {
    bulkRequestBody: BulkRequestBody;
}

export interface CollectionApiCollectionCancelRequest {
    id: number;
}

export interface CollectionApiCollectionDecideOperationRequest {
    id: number;
    collectionDecideRequest: CollectionDecideRequest;
}

export interface CollectionApiCollectionDeleteRequest {
    id: number;
}

export interface CollectionApiCollectionDownloadRequest {
    id: number;
}

export interface CollectionApiCollectionListRequest {
    name?: string;
    originalId?: string;
    transferId?: string;
    aipId?: string;
    pipelineId?: string;
    earliestCreatedTime?: Date;
    latestCreatedTime?: Date;
    status?: CollectionListStatusEnum;
    cursor?: string;
}

export interface CollectionApiCollectionRetryRequest {
    id: number;
}

export interface CollectionApiCollectionShowRequest {
    id: number;
}

export interface CollectionApiCollectionWorkflowRequest {
    id: number;
}

/**
 * CollectionApi - interface
 * 
 * @export
 * @interface CollectionApiInterface
 */
export interface CollectionApiInterface {
    /**
     * Bulk operations (retry, cancel...).
     * @summary bulk collection
     * @param {BulkRequestBody} bulkRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionBulkRaw(requestParameters: CollectionApiCollectionBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkResult>>;

    /**
     * Bulk operations (retry, cancel...).
     * bulk collection
     */
    collectionBulk(requestParameters: CollectionApiCollectionBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkResult>;

    /**
     * Retrieve status of current bulk operation.
     * @summary bulk_status collection
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionBulkStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkStatusResult>>;

    /**
     * Retrieve status of current bulk operation.
     * bulk_status collection
     */
    collectionBulkStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkStatusResult>;

    /**
     * Cancel collection processing by ID
     * @summary cancel collection
     * @param {number} id Identifier of collection to remove
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionCancelRaw(requestParameters: CollectionApiCollectionCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Cancel collection processing by ID
     * cancel collection
     */
    collectionCancel(requestParameters: CollectionApiCollectionCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Make decision for a pending collection by ID
     * @summary decide collection
     * @param {number} id Identifier of collection to look up
     * @param {CollectionDecideRequest} collectionDecideRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionDecideRaw(requestParameters: CollectionApiCollectionDecideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Make decision for a pending collection by ID
     * decide collection
     */
    collectionDecide(requestParameters: CollectionApiCollectionDecideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Delete collection by ID
     * @summary delete collection
     * @param {number} id Identifier of collection to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionDeleteRaw(requestParameters: CollectionApiCollectionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete collection by ID
     * delete collection
     */
    collectionDelete(requestParameters: CollectionApiCollectionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Download collection by ID
     * @summary download collection
     * @param {number} id Identifier of collection to look up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionDownloadRaw(requestParameters: CollectionApiCollectionDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Download collection by ID
     * download collection
     */
    collectionDownload(requestParameters: CollectionApiCollectionDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * List all stored collections
     * @summary list collection
     * @param {string} [name] 
     * @param {string} [originalId] 
     * @param {string} [transferId] Identifier of Archivematica tranfser
     * @param {string} [aipId] Identifier of Archivematica AIP
     * @param {string} [pipelineId] Identifier of Archivematica pipeline
     * @param {Date} [earliestCreatedTime] 
     * @param {Date} [latestCreatedTime] 
     * @param {'new' | 'in progress' | 'done' | 'error' | 'unknown' | 'queued' | 'pending' | 'abandoned'} [status] 
     * @param {string} [cursor] Pagination cursor
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionListRaw(requestParameters: CollectionApiCollectionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseBody>>;

    /**
     * List all stored collections
     * list collection
     */
    collectionList(requestParameters: CollectionApiCollectionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseBody>;

    /**
     * 
     * @summary monitor collection
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionMonitorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * monitor collection
     */
    collectionMonitor(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Retry collection processing by ID
     * @summary retry collection
     * @param {number} id Identifier of collection to retry
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionRetryRaw(requestParameters: CollectionApiCollectionRetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetryResult>>;

    /**
     * Retry collection processing by ID
     * retry collection
     */
    collectionRetry(requestParameters: CollectionApiCollectionRetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetryResult>;

    /**
     * Show collection by ID
     * @summary show collection
     * @param {number} id Identifier of collection to show
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionShowRaw(requestParameters: CollectionApiCollectionShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroDetailedStoredCollection>>;

    /**
     * Show collection by ID
     * show collection
     */
    collectionShow(requestParameters: CollectionApiCollectionShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroDetailedStoredCollection>;

    /**
     * Retrieve workflow status by ID
     * @summary workflow collection
     * @param {number} id Identifier of collection to look up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionWorkflowRaw(requestParameters: CollectionApiCollectionWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroCollectionWorkflowStatus>>;

    /**
     * Retrieve workflow status by ID
     * workflow collection
     */
    collectionWorkflow(requestParameters: CollectionApiCollectionWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroCollectionWorkflowStatus>;

}

/**
 * 
 */
export class CollectionApi extends runtime.BaseAPI implements CollectionApiInterface {

    /**
     * Bulk operations (retry, cancel...).
     * bulk collection
     */
    async collectionBulkRaw(requestParameters: CollectionApiCollectionBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkResult>> {
        if (requestParameters['bulkRequestBody'] == null) {
            throw new runtime.RequiredError(
                'bulkRequestBody',
                'Required parameter "bulkRequestBody" was null or undefined when calling collectionBulk().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/collection/bulk`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkRequestBodyToJSON(requestParameters['bulkRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkResultFromJSON(jsonValue));
    }

    /**
     * Bulk operations (retry, cancel...).
     * bulk collection
     */
    async collectionBulk(requestParameters: CollectionApiCollectionBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkResult> {
        const response = await this.collectionBulkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve status of current bulk operation.
     * bulk_status collection
     */
    async collectionBulkStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkStatusResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/bulk`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkStatusResultFromJSON(jsonValue));
    }

    /**
     * Retrieve status of current bulk operation.
     * bulk_status collection
     */
    async collectionBulkStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkStatusResult> {
        const response = await this.collectionBulkStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Cancel collection processing by ID
     * cancel collection
     */
    async collectionCancelRaw(requestParameters: CollectionApiCollectionCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionCancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}/cancel`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancel collection processing by ID
     * cancel collection
     */
    async collectionCancel(requestParameters: CollectionApiCollectionCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.collectionCancelRaw(requestParameters, initOverrides);
    }

    /**
     * Make decision for a pending collection by ID
     * decide collection
     */
    async collectionDecideRaw(requestParameters: CollectionApiCollectionDecideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionDecide().'
            );
        }

        if (requestParameters['collectionDecideRequest'] == null) {
            throw new runtime.RequiredError(
                'collectionDecideRequest',
                'Required parameter "collectionDecideRequest" was null or undefined when calling collectionDecide().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/collection/{id}/decision`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionDecideRequestToJSON(requestParameters['collectionDecideRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Make decision for a pending collection by ID
     * decide collection
     */
    async collectionDecide(requestParameters: CollectionApiCollectionDecideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.collectionDecideRaw(requestParameters, initOverrides);
    }

    /**
     * Delete collection by ID
     * delete collection
     */
    async collectionDeleteRaw(requestParameters: CollectionApiCollectionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete collection by ID
     * delete collection
     */
    async collectionDelete(requestParameters: CollectionApiCollectionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.collectionDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Download collection by ID
     * download collection
     */
    async collectionDownloadRaw(requestParameters: CollectionApiCollectionDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionDownload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}/download`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download collection by ID
     * download collection
     */
    async collectionDownload(requestParameters: CollectionApiCollectionDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.collectionDownloadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all stored collections
     * list collection
     */
    async collectionListRaw(requestParameters: CollectionApiCollectionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseBody>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['originalId'] != null) {
            queryParameters['original_id'] = requestParameters['originalId'];
        }

        if (requestParameters['transferId'] != null) {
            queryParameters['transfer_id'] = requestParameters['transferId'];
        }

        if (requestParameters['aipId'] != null) {
            queryParameters['aip_id'] = requestParameters['aipId'];
        }

        if (requestParameters['pipelineId'] != null) {
            queryParameters['pipeline_id'] = requestParameters['pipelineId'];
        }

        if (requestParameters['earliestCreatedTime'] != null) {
            queryParameters['earliest_created_time'] = (requestParameters['earliestCreatedTime'] as any).toISOString();
        }

        if (requestParameters['latestCreatedTime'] != null) {
            queryParameters['latest_created_time'] = (requestParameters['latestCreatedTime'] as any).toISOString();
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseBodyFromJSON(jsonValue));
    }

    /**
     * List all stored collections
     * list collection
     */
    async collectionList(requestParameters: CollectionApiCollectionListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseBody> {
        const response = await this.collectionListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * monitor collection
     */
    async collectionMonitorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/monitor`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * monitor collection
     */
    async collectionMonitor(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.collectionMonitorRaw(initOverrides);
    }

    /**
     * Retry collection processing by ID
     * retry collection
     */
    async collectionRetryRaw(requestParameters: CollectionApiCollectionRetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetryResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionRetry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}/retry`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RetryResultFromJSON(jsonValue));
    }

    /**
     * Retry collection processing by ID
     * retry collection
     */
    async collectionRetry(requestParameters: CollectionApiCollectionRetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetryResult> {
        const response = await this.collectionRetryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show collection by ID
     * show collection
     */
    async collectionShowRaw(requestParameters: CollectionApiCollectionShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroDetailedStoredCollection>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroDetailedStoredCollectionFromJSON(jsonValue));
    }

    /**
     * Show collection by ID
     * show collection
     */
    async collectionShow(requestParameters: CollectionApiCollectionShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroDetailedStoredCollection> {
        const response = await this.collectionShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve workflow status by ID
     * workflow collection
     */
    async collectionWorkflowRaw(requestParameters: CollectionApiCollectionWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroCollectionWorkflowStatus>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}/workflow`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroCollectionWorkflowStatusFromJSON(jsonValue));
    }

    /**
     * Retrieve workflow status by ID
     * workflow collection
     */
    async collectionWorkflow(requestParameters: CollectionApiCollectionWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroCollectionWorkflowStatus> {
        const response = await this.collectionWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum CollectionListStatusEnum {
    New = 'new',
    InProgress = 'in progress',
    Done = 'done',
    Error = 'error',
    Unknown = 'unknown',
    Queued = 'queued',
    Pending = 'pending',
    Abandoned = 'abandoned',
    UnknownDefaultOpenApi = '11184809'
}
