/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EnduroCollectionWorkflowHistoryResponseBody,
    EnduroCollectionWorkflowHistoryResponseBodyFromJSON,
    EnduroCollectionWorkflowHistoryResponseBodyFromJSONTyped,
    EnduroCollectionWorkflowHistoryResponseBodyToJSON,
} from './EnduroCollectionWorkflowHistoryResponseBody';

/**
 * WorkflowResponseBody result type (default view)
 * @export
 * @interface CollectionWorkflowResponseBody
 */
export interface CollectionWorkflowResponseBody {
    /**
     * EnduroCollection-Workflow-HistoryCollectionResponseBody is the result type for an array of EnduroCollection-Workflow-HistoryResponseBody (default view)
     * @type {Array<EnduroCollectionWorkflowHistoryResponseBody>}
     * @memberof CollectionWorkflowResponseBody
     */
    history?: Array<EnduroCollectionWorkflowHistoryResponseBody>;
    /**
     * 
     * @type {string}
     * @memberof CollectionWorkflowResponseBody
     */
    status?: string;
}

export function CollectionWorkflowResponseBodyFromJSON(json: any): CollectionWorkflowResponseBody {
    return CollectionWorkflowResponseBodyFromJSONTyped(json, false);
}

export function CollectionWorkflowResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionWorkflowResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'history': !exists(json, 'history') ? undefined : ((json['history'] as Array<any>).map(EnduroCollectionWorkflowHistoryResponseBodyFromJSON)),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function CollectionWorkflowResponseBodyToJSON(value?: CollectionWorkflowResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'history': value.history === undefined ? undefined : ((value.history as Array<any>).map(EnduroCollectionWorkflowHistoryResponseBodyToJSON)),
        'status': value.status,
    };
}

