// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artefactual-labs/enduro/internal/amclient (interfaces: PackageService)

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	reflect "reflect"

	amclient "github.com/artefactual-labs/enduro/internal/amclient"
	gomock "go.uber.org/mock/gomock"
)

// MockPackageService is a mock of PackageService interface.
type MockPackageService struct {
	ctrl     *gomock.Controller
	recorder *MockPackageServiceMockRecorder
}

// MockPackageServiceMockRecorder is the mock recorder for MockPackageService.
type MockPackageServiceMockRecorder struct {
	mock *MockPackageService
}

// NewMockPackageService creates a new mock instance.
func NewMockPackageService(ctrl *gomock.Controller) *MockPackageService {
	mock := &MockPackageService{ctrl: ctrl}
	mock.recorder = &MockPackageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageService) EXPECT() *MockPackageServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPackageService) Create(arg0 context.Context, arg1 *amclient.PackageCreateRequest) (*amclient.PackageCreateResponse, *amclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*amclient.PackageCreateResponse)
	ret1, _ := ret[1].(*amclient.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockPackageServiceMockRecorder) Create(arg0, arg1 interface{}) *PackageServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPackageService)(nil).Create), arg0, arg1)
	return &PackageServiceCreateCall{Call: call}
}

// PackageServiceCreateCall wrap *gomock.Call
type PackageServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PackageServiceCreateCall) Return(arg0 *amclient.PackageCreateResponse, arg1 *amclient.Response, arg2 error) *PackageServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PackageServiceCreateCall) Do(f func(context.Context, *amclient.PackageCreateRequest) (*amclient.PackageCreateResponse, *amclient.Response, error)) *PackageServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PackageServiceCreateCall) DoAndReturn(f func(context.Context, *amclient.PackageCreateRequest) (*amclient.PackageCreateResponse, *amclient.Response, error)) *PackageServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
