/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BatchBrowseResult,
  BatchHintsResult,
  BatchResult,
  BatchStatusResult,
  SubmitRequestBody,
} from '../models/index';
import {
    BatchBrowseResultFromJSON,
    BatchBrowseResultToJSON,
    BatchHintsResultFromJSON,
    BatchHintsResultToJSON,
    BatchResultFromJSON,
    BatchResultToJSON,
    BatchStatusResultFromJSON,
    BatchStatusResultToJSON,
    SubmitRequestBodyFromJSON,
    SubmitRequestBodyToJSON,
} from '../models/index';

export interface BatchBrowseRequest {
    path?: string;
}

export interface BatchSubmitRequest {
    submitRequestBody: SubmitRequestBody;
}

/**
 * BatchApi - interface
 * 
 * @export
 * @interface BatchApiInterface
 */
export interface BatchApiInterface {
    /**
     * Browse batch source directories
     * @summary browse batch
     * @param {string} [path] Root-relative directory path to list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BatchApiInterface
     */
    batchBrowseRaw(requestParameters: BatchBrowseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchBrowseResult>>;

    /**
     * Browse batch source directories
     * browse batch
     */
    batchBrowse(requestParameters: BatchBrowseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchBrowseResult>;

    /**
     * Retrieve form hints
     * @summary hints batch
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BatchApiInterface
     */
    batchHintsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchHintsResult>>;

    /**
     * Retrieve form hints
     * hints batch
     */
    batchHints(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchHintsResult>;

    /**
     * Retrieve status of current batch operation.
     * @summary status batch
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BatchApiInterface
     */
    batchStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchStatusResult>>;

    /**
     * Retrieve status of current batch operation.
     * status batch
     */
    batchStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchStatusResult>;

    /**
     * Submit a new batch
     * @summary submit batch
     * @param {SubmitRequestBody} submitRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BatchApiInterface
     */
    batchSubmitRaw(requestParameters: BatchSubmitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchResult>>;

    /**
     * Submit a new batch
     * submit batch
     */
    batchSubmit(requestParameters: BatchSubmitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchResult>;

}

/**
 * 
 */
export class BatchApi extends runtime.BaseAPI implements BatchApiInterface {

    /**
     * Browse batch source directories
     * browse batch
     */
    async batchBrowseRaw(requestParameters: BatchBrowseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchBrowseResult>> {
        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/batch/browser`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchBrowseResultFromJSON(jsonValue));
    }

    /**
     * Browse batch source directories
     * browse batch
     */
    async batchBrowse(requestParameters: BatchBrowseRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchBrowseResult> {
        const response = await this.batchBrowseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve form hints
     * hints batch
     */
    async batchHintsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchHintsResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/batch/hints`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchHintsResultFromJSON(jsonValue));
    }

    /**
     * Retrieve form hints
     * hints batch
     */
    async batchHints(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchHintsResult> {
        const response = await this.batchHintsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve status of current batch operation.
     * status batch
     */
    async batchStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchStatusResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchStatusResultFromJSON(jsonValue));
    }

    /**
     * Retrieve status of current batch operation.
     * status batch
     */
    async batchStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchStatusResult> {
        const response = await this.batchStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Submit a new batch
     * submit batch
     */
    async batchSubmitRaw(requestParameters: BatchSubmitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchResult>> {
        if (requestParameters['submitRequestBody'] == null) {
            throw new runtime.RequiredError(
                'submitRequestBody',
                'Required parameter "submitRequestBody" was null or undefined when calling batchSubmit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitRequestBodyToJSON(requestParameters['submitRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchResultFromJSON(jsonValue));
    }

    /**
     * Submit a new batch
     * submit batch
     */
    async batchSubmit(requestParameters: BatchSubmitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchResult> {
        const response = await this.batchSubmitRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
