/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BulkRequestBody,
    BulkRequestBodyFromJSON,
    BulkRequestBodyToJSON,
} from '../models/BulkRequestBody';
import {
    type BulkResult,
    BulkResultFromJSON,
    BulkResultToJSON,
} from '../models/BulkResult';
import {
    type BulkStatusResult,
    BulkStatusResultFromJSON,
    BulkStatusResultToJSON,
} from '../models/BulkStatusResult';
import {
    type CollectionDecideRequest,
    CollectionDecideRequestFromJSON,
    CollectionDecideRequestToJSON,
} from '../models/CollectionDecideRequest';
import {
    type CollectionNotfound,
    CollectionNotfoundFromJSON,
    CollectionNotfoundToJSON,
} from '../models/CollectionNotfound';
import {
    type EnduroCollectionStatusHistory,
    EnduroCollectionStatusHistoryFromJSON,
    EnduroCollectionStatusHistoryToJSON,
} from '../models/EnduroCollectionStatusHistory';
import {
    type EnduroCollectionWorkflowStatus,
    EnduroCollectionWorkflowStatusFromJSON,
    EnduroCollectionWorkflowStatusToJSON,
} from '../models/EnduroCollectionWorkflowStatus';
import {
    type EnduroDetailedStoredCollection,
    EnduroDetailedStoredCollectionFromJSON,
    EnduroDetailedStoredCollectionToJSON,
} from '../models/EnduroDetailedStoredCollection';
import {
    type EnduroMonitorUpdate,
    EnduroMonitorUpdateFromJSON,
    EnduroMonitorUpdateToJSON,
} from '../models/EnduroMonitorUpdate';
import {
    type ListResponseBody,
    ListResponseBodyFromJSON,
    ListResponseBodyToJSON,
} from '../models/ListResponseBody';
import {
    type RetryResult,
    RetryResultFromJSON,
    RetryResultToJSON,
} from '../models/RetryResult';

export interface CollectionBulkRequest {
    bulkRequestBody: BulkRequestBody;
}

export interface CollectionCancelRequest {
    id: number;
}

export interface CollectionDecideOperationRequest {
    id: number;
    collectionDecideRequest: CollectionDecideRequest;
}

export interface CollectionDeleteRequest {
    id: number;
}

export interface CollectionDownloadRequest {
    id: number;
}

export interface CollectionListRequest {
    name?: string;
    originalId?: string;
    transferId?: string;
    aipId?: string;
    pipelineId?: string;
    earliestCreatedTime?: Date;
    latestCreatedTime?: Date;
    status?: CollectionListStatusEnum;
    cursor?: string;
}

export interface CollectionRetryRequest {
    id: number;
}

export interface CollectionShowRequest {
    id: number;
}

export interface CollectionStatusHistoryRequest {
    id: number;
}

export interface CollectionWorkflowRequest {
    id: number;
}

/**
 * CollectionApi - interface
 * 
 * @export
 * @interface CollectionApiInterface
 */
export interface CollectionApiInterface {
    /**
     * Creates request options for collectionBulk without sending the request
     * @param {BulkRequestBody} bulkRequestBody Request body for bulk.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionBulkRequestOpts(requestParameters: CollectionBulkRequest): Promise<runtime.RequestOpts>;

    /**
     * Bulk operations (retry, cancel...).
     * @summary bulk collection
     * @param {BulkRequestBody} bulkRequestBody Request body for bulk.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionBulkRaw(requestParameters: CollectionBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkResult>>;

    /**
     * Bulk operations (retry, cancel...).
     * bulk collection
     */
    collectionBulk(requestParameters: CollectionBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkResult>;

    /**
     * Creates request options for collectionBulkStatus without sending the request
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionBulkStatusRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Retrieve status of current bulk operation.
     * @summary bulk_status collection
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionBulkStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkStatusResult>>;

    /**
     * Retrieve status of current bulk operation.
     * bulk_status collection
     */
    collectionBulkStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkStatusResult>;

    /**
     * Creates request options for collectionCancel without sending the request
     * @param {number} id Identifier of collection to remove
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionCancelRequestOpts(requestParameters: CollectionCancelRequest): Promise<runtime.RequestOpts>;

    /**
     * Cancel collection processing by ID
     * @summary cancel collection
     * @param {number} id Identifier of collection to remove
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionCancelRaw(requestParameters: CollectionCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Cancel collection processing by ID
     * cancel collection
     */
    collectionCancel(requestParameters: CollectionCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for collectionDecide without sending the request
     * @param {number} id Identifier of collection to look up
     * @param {CollectionDecideRequest} collectionDecideRequest Request body for decide.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionDecideRequestOpts(requestParameters: CollectionDecideOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Make decision for a pending collection by ID
     * @summary decide collection
     * @param {number} id Identifier of collection to look up
     * @param {CollectionDecideRequest} collectionDecideRequest Request body for decide.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionDecideRaw(requestParameters: CollectionDecideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Make decision for a pending collection by ID
     * decide collection
     */
    collectionDecide(requestParameters: CollectionDecideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for collectionDelete without sending the request
     * @param {number} id Identifier of collection to delete
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionDeleteRequestOpts(requestParameters: CollectionDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Delete collection by ID
     * @summary delete collection
     * @param {number} id Identifier of collection to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionDeleteRaw(requestParameters: CollectionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete collection by ID
     * delete collection
     */
    collectionDelete(requestParameters: CollectionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for collectionDownload without sending the request
     * @param {number} id Identifier of collection to look up
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionDownloadRequestOpts(requestParameters: CollectionDownloadRequest): Promise<runtime.RequestOpts>;

    /**
     * Download collection by ID
     * @summary download collection
     * @param {number} id Identifier of collection to look up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionDownloadRaw(requestParameters: CollectionDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Download collection by ID
     * download collection
     */
    collectionDownload(requestParameters: CollectionDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for collectionList without sending the request
     * @param {string} [name] 
     * @param {string} [originalId] 
     * @param {string} [transferId] Identifier of Archivematica tranfser
     * @param {string} [aipId] Identifier of Archivematica AIP
     * @param {string} [pipelineId] Identifier of Archivematica pipeline
     * @param {Date} [earliestCreatedTime] 
     * @param {Date} [latestCreatedTime] 
     * @param {'new' | 'in progress' | 'done' | 'error' | 'unknown' | 'queued' | 'pending' | 'abandoned'} [status] 
     * @param {string} [cursor] Pagination cursor
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionListRequestOpts(requestParameters: CollectionListRequest): Promise<runtime.RequestOpts>;

    /**
     * List all stored collections
     * @summary list collection
     * @param {string} [name] 
     * @param {string} [originalId] 
     * @param {string} [transferId] Identifier of Archivematica tranfser
     * @param {string} [aipId] Identifier of Archivematica AIP
     * @param {string} [pipelineId] Identifier of Archivematica pipeline
     * @param {Date} [earliestCreatedTime] 
     * @param {Date} [latestCreatedTime] 
     * @param {'new' | 'in progress' | 'done' | 'error' | 'unknown' | 'queued' | 'pending' | 'abandoned'} [status] 
     * @param {string} [cursor] Pagination cursor
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionListRaw(requestParameters: CollectionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseBody>>;

    /**
     * List all stored collections
     * list collection
     */
    collectionList(requestParameters: CollectionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseBody>;

    /**
     * Creates request options for collectionMonitor without sending the request
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionMonitorRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary monitor collection
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionMonitorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroMonitorUpdate>>;

    /**
     * monitor collection
     */
    collectionMonitor(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroMonitorUpdate>;

    /**
     * Creates request options for collectionRetry without sending the request
     * @param {number} id Identifier of collection to retry
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionRetryRequestOpts(requestParameters: CollectionRetryRequest): Promise<runtime.RequestOpts>;

    /**
     * Retry collection processing by ID
     * @summary retry collection
     * @param {number} id Identifier of collection to retry
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionRetryRaw(requestParameters: CollectionRetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetryResult>>;

    /**
     * Retry collection processing by ID
     * retry collection
     */
    collectionRetry(requestParameters: CollectionRetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetryResult>;

    /**
     * Creates request options for collectionShow without sending the request
     * @param {number} id Identifier of collection to show
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionShowRequestOpts(requestParameters: CollectionShowRequest): Promise<runtime.RequestOpts>;

    /**
     * Show collection by ID
     * @summary show collection
     * @param {number} id Identifier of collection to show
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionShowRaw(requestParameters: CollectionShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroDetailedStoredCollection>>;

    /**
     * Show collection by ID
     * show collection
     */
    collectionShow(requestParameters: CollectionShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroDetailedStoredCollection>;

    /**
     * Creates request options for collectionStatusHistory without sending the request
     * @param {number} id Identifier of collection to look up
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionStatusHistoryRequestOpts(requestParameters: CollectionStatusHistoryRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieve the recorded status transition history for a collection
     * @summary status_history collection
     * @param {number} id Identifier of collection to look up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionStatusHistoryRaw(requestParameters: CollectionStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroCollectionStatusHistory>>;

    /**
     * Retrieve the recorded status transition history for a collection
     * status_history collection
     */
    collectionStatusHistory(requestParameters: CollectionStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroCollectionStatusHistory>;

    /**
     * Creates request options for collectionWorkflow without sending the request
     * @param {number} id Identifier of collection to look up
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionWorkflowRequestOpts(requestParameters: CollectionWorkflowRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieve workflow status by ID
     * @summary workflow collection
     * @param {number} id Identifier of collection to look up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionApiInterface
     */
    collectionWorkflowRaw(requestParameters: CollectionWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroCollectionWorkflowStatus>>;

    /**
     * Retrieve workflow status by ID
     * workflow collection
     */
    collectionWorkflow(requestParameters: CollectionWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroCollectionWorkflowStatus>;

}

/**
 * 
 */
export class CollectionApi extends runtime.BaseAPI implements CollectionApiInterface {

    /**
     * Creates request options for collectionBulk without sending the request
     */
    async collectionBulkRequestOpts(requestParameters: CollectionBulkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bulkRequestBody'] == null) {
            throw new runtime.RequiredError(
                'bulkRequestBody',
                'Required parameter "bulkRequestBody" was null or undefined when calling collectionBulk().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/collection/bulk`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkRequestBodyToJSON(requestParameters['bulkRequestBody']),
        };
    }

    /**
     * Bulk operations (retry, cancel...).
     * bulk collection
     */
    async collectionBulkRaw(requestParameters: CollectionBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkResult>> {
        const requestOptions = await this.collectionBulkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkResultFromJSON(jsonValue));
    }

    /**
     * Bulk operations (retry, cancel...).
     * bulk collection
     */
    async collectionBulk(requestParameters: CollectionBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkResult> {
        const response = await this.collectionBulkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionBulkStatus without sending the request
     */
    async collectionBulkStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/bulk`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve status of current bulk operation.
     * bulk_status collection
     */
    async collectionBulkStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkStatusResult>> {
        const requestOptions = await this.collectionBulkStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkStatusResultFromJSON(jsonValue));
    }

    /**
     * Retrieve status of current bulk operation.
     * bulk_status collection
     */
    async collectionBulkStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkStatusResult> {
        const response = await this.collectionBulkStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionCancel without sending the request
     */
    async collectionCancelRequestOpts(requestParameters: CollectionCancelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionCancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}/cancel`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel collection processing by ID
     * cancel collection
     */
    async collectionCancelRaw(requestParameters: CollectionCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.collectionCancelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancel collection processing by ID
     * cancel collection
     */
    async collectionCancel(requestParameters: CollectionCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.collectionCancelRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for collectionDecide without sending the request
     */
    async collectionDecideRequestOpts(requestParameters: CollectionDecideOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionDecide().'
            );
        }

        if (requestParameters['collectionDecideRequest'] == null) {
            throw new runtime.RequiredError(
                'collectionDecideRequest',
                'Required parameter "collectionDecideRequest" was null or undefined when calling collectionDecide().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/collection/{id}/decision`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionDecideRequestToJSON(requestParameters['collectionDecideRequest']),
        };
    }

    /**
     * Make decision for a pending collection by ID
     * decide collection
     */
    async collectionDecideRaw(requestParameters: CollectionDecideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.collectionDecideRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Make decision for a pending collection by ID
     * decide collection
     */
    async collectionDecide(requestParameters: CollectionDecideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.collectionDecideRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for collectionDelete without sending the request
     */
    async collectionDeleteRequestOpts(requestParameters: CollectionDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete collection by ID
     * delete collection
     */
    async collectionDeleteRaw(requestParameters: CollectionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.collectionDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete collection by ID
     * delete collection
     */
    async collectionDelete(requestParameters: CollectionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.collectionDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for collectionDownload without sending the request
     */
    async collectionDownloadRequestOpts(requestParameters: CollectionDownloadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionDownload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}/download`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download collection by ID
     * download collection
     */
    async collectionDownloadRaw(requestParameters: CollectionDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.collectionDownloadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download collection by ID
     * download collection
     */
    async collectionDownload(requestParameters: CollectionDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.collectionDownloadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionList without sending the request
     */
    async collectionListRequestOpts(requestParameters: CollectionListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['originalId'] != null) {
            queryParameters['original_id'] = requestParameters['originalId'];
        }

        if (requestParameters['transferId'] != null) {
            queryParameters['transfer_id'] = requestParameters['transferId'];
        }

        if (requestParameters['aipId'] != null) {
            queryParameters['aip_id'] = requestParameters['aipId'];
        }

        if (requestParameters['pipelineId'] != null) {
            queryParameters['pipeline_id'] = requestParameters['pipelineId'];
        }

        if (requestParameters['earliestCreatedTime'] != null) {
            queryParameters['earliest_created_time'] = (requestParameters['earliestCreatedTime'] as any).toISOString();
        }

        if (requestParameters['latestCreatedTime'] != null) {
            queryParameters['latest_created_time'] = (requestParameters['latestCreatedTime'] as any).toISOString();
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all stored collections
     * list collection
     */
    async collectionListRaw(requestParameters: CollectionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseBody>> {
        const requestOptions = await this.collectionListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseBodyFromJSON(jsonValue));
    }

    /**
     * List all stored collections
     * list collection
     */
    async collectionList(requestParameters: CollectionListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseBody> {
        const response = await this.collectionListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionMonitor without sending the request
     */
    async collectionMonitorRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/monitor`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * monitor collection
     */
    async collectionMonitorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroMonitorUpdate>> {
        const requestOptions = await this.collectionMonitorRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroMonitorUpdateFromJSON(jsonValue));
    }

    /**
     * monitor collection
     */
    async collectionMonitor(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroMonitorUpdate> {
        const response = await this.collectionMonitorRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionRetry without sending the request
     */
    async collectionRetryRequestOpts(requestParameters: CollectionRetryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionRetry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}/retry`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retry collection processing by ID
     * retry collection
     */
    async collectionRetryRaw(requestParameters: CollectionRetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetryResult>> {
        const requestOptions = await this.collectionRetryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RetryResultFromJSON(jsonValue));
    }

    /**
     * Retry collection processing by ID
     * retry collection
     */
    async collectionRetry(requestParameters: CollectionRetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetryResult> {
        const response = await this.collectionRetryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionShow without sending the request
     */
    async collectionShowRequestOpts(requestParameters: CollectionShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show collection by ID
     * show collection
     */
    async collectionShowRaw(requestParameters: CollectionShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroDetailedStoredCollection>> {
        const requestOptions = await this.collectionShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroDetailedStoredCollectionFromJSON(jsonValue));
    }

    /**
     * Show collection by ID
     * show collection
     */
    async collectionShow(requestParameters: CollectionShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroDetailedStoredCollection> {
        const response = await this.collectionShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionStatusHistory without sending the request
     */
    async collectionStatusHistoryRequestOpts(requestParameters: CollectionStatusHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionStatusHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}/status-history`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve the recorded status transition history for a collection
     * status_history collection
     */
    async collectionStatusHistoryRaw(requestParameters: CollectionStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroCollectionStatusHistory>> {
        const requestOptions = await this.collectionStatusHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroCollectionStatusHistoryFromJSON(jsonValue));
    }

    /**
     * Retrieve the recorded status transition history for a collection
     * status_history collection
     */
    async collectionStatusHistory(requestParameters: CollectionStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroCollectionStatusHistory> {
        const response = await this.collectionStatusHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionWorkflow without sending the request
     */
    async collectionWorkflowRequestOpts(requestParameters: CollectionWorkflowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collection/{id}/workflow`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve workflow status by ID
     * workflow collection
     */
    async collectionWorkflowRaw(requestParameters: CollectionWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroCollectionWorkflowStatus>> {
        const requestOptions = await this.collectionWorkflowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroCollectionWorkflowStatusFromJSON(jsonValue));
    }

    /**
     * Retrieve workflow status by ID
     * workflow collection
     */
    async collectionWorkflow(requestParameters: CollectionWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroCollectionWorkflowStatus> {
        const response = await this.collectionWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CollectionListStatusEnum = {
    New: 'new',
    InProgress: 'in progress',
    Done: 'done',
    Error: 'error',
    Unknown: 'unknown',
    Queued: 'queued',
    Pending: 'pending',
    Abandoned: 'abandoned'
} as const;
export type CollectionListStatusEnum = typeof CollectionListStatusEnum[keyof typeof CollectionListStatusEnum];
