/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type EnduroStoredPipeline,
    EnduroStoredPipelineFromJSON,
    EnduroStoredPipelineToJSON,
} from '../models/EnduroStoredPipeline';
import {
    type PipelineNotFound,
    PipelineNotFoundFromJSON,
    PipelineNotFoundToJSON,
} from '../models/PipelineNotFound';

export interface PipelineListRequest {
    name?: string;
    status?: boolean;
}

export interface PipelineProcessingRequest {
    id: string;
}

export interface PipelineShowRequest {
    id: string;
}

/**
 * PipelineApi - interface
 * 
 * @export
 * @interface PipelineApiInterface
 */
export interface PipelineApiInterface {
    /**
     * Creates request options for pipelineList without sending the request
     * @param {string} [name] 
     * @param {boolean} [status] 
     * @throws {RequiredError}
     * @memberof PipelineApiInterface
     */
    pipelineListRequestOpts(requestParameters: PipelineListRequest): Promise<runtime.RequestOpts>;

    /**
     * List all known pipelines
     * @summary list pipeline
     * @param {string} [name] 
     * @param {boolean} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineApiInterface
     */
    pipelineListRaw(requestParameters: PipelineListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EnduroStoredPipeline>>>;

    /**
     * List all known pipelines
     * list pipeline
     */
    pipelineList(requestParameters: PipelineListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EnduroStoredPipeline>>;

    /**
     * Creates request options for pipelineProcessing without sending the request
     * @param {string} id Identifier of pipeline
     * @throws {RequiredError}
     * @memberof PipelineApiInterface
     */
    pipelineProcessingRequestOpts(requestParameters: PipelineProcessingRequest): Promise<runtime.RequestOpts>;

    /**
     * List all processing configurations of a pipeline given its ID
     * @summary processing pipeline
     * @param {string} id Identifier of pipeline
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineApiInterface
     */
    pipelineProcessingRaw(requestParameters: PipelineProcessingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * List all processing configurations of a pipeline given its ID
     * processing pipeline
     */
    pipelineProcessing(requestParameters: PipelineProcessingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

    /**
     * Creates request options for pipelineShow without sending the request
     * @param {string} id Identifier of pipeline to show
     * @throws {RequiredError}
     * @memberof PipelineApiInterface
     */
    pipelineShowRequestOpts(requestParameters: PipelineShowRequest): Promise<runtime.RequestOpts>;

    /**
     * Show pipeline by ID
     * @summary show pipeline
     * @param {string} id Identifier of pipeline to show
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineApiInterface
     */
    pipelineShowRaw(requestParameters: PipelineShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroStoredPipeline>>;

    /**
     * Show pipeline by ID
     * show pipeline
     */
    pipelineShow(requestParameters: PipelineShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroStoredPipeline>;

}

/**
 * 
 */
export class PipelineApi extends runtime.BaseAPI implements PipelineApiInterface {

    /**
     * Creates request options for pipelineList without sending the request
     */
    async pipelineListRequestOpts(requestParameters: PipelineListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pipeline`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all known pipelines
     * list pipeline
     */
    async pipelineListRaw(requestParameters: PipelineListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EnduroStoredPipeline>>> {
        const requestOptions = await this.pipelineListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EnduroStoredPipelineFromJSON));
    }

    /**
     * List all known pipelines
     * list pipeline
     */
    async pipelineList(requestParameters: PipelineListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EnduroStoredPipeline>> {
        const response = await this.pipelineListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pipelineProcessing without sending the request
     */
    async pipelineProcessingRequestOpts(requestParameters: PipelineProcessingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pipelineProcessing().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pipeline/{id}/processing`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all processing configurations of a pipeline given its ID
     * processing pipeline
     */
    async pipelineProcessingRaw(requestParameters: PipelineProcessingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.pipelineProcessingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List all processing configurations of a pipeline given its ID
     * processing pipeline
     */
    async pipelineProcessing(requestParameters: PipelineProcessingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.pipelineProcessingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pipelineShow without sending the request
     */
    async pipelineShowRequestOpts(requestParameters: PipelineShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pipelineShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pipeline/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show pipeline by ID
     * show pipeline
     */
    async pipelineShowRaw(requestParameters: PipelineShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroStoredPipeline>> {
        const requestOptions = await this.pipelineShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroStoredPipelineFromJSON(jsonValue));
    }

    /**
     * Show pipeline by ID
     * show pipeline
     */
    async pipelineShow(requestParameters: PipelineShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroStoredPipeline> {
        const response = await this.pipelineShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
