/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * no description
 */
export class SwaggerApi extends runtime.BaseAPI {

    /**
     * JSON document containing the API swagger definition.
     * Download internal/api/gen/http/openapi.json
     */
    async swaggerSwaggerSwaggerJsonRaw(): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/swagger/swagger.json`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.BlobApiResponse(response);
    }

    /**
     * JSON document containing the API swagger definition.
     * Download internal/api/gen/http/openapi.json
     */
    async swaggerSwaggerSwaggerJson(): Promise<Blob> {
        const response = await this.swaggerSwaggerSwaggerJsonRaw();
        return await response.value();
    }

}
