/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * SwaggerApi - interface
 * 
 * @export
 * @interface SwaggerApiInterface
 */
export interface SwaggerApiInterface {
    /**
     * JSON document containing the API swagger definition.
     * @summary Download internal/api/gen/http/openapi.json
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SwaggerApiInterface
     */
    swaggerSwaggerSwaggerJsonRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * JSON document containing the API swagger definition.
     * Download internal/api/gen/http/openapi.json
     */
    swaggerSwaggerSwaggerJson(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class SwaggerApi extends runtime.BaseAPI implements SwaggerApiInterface {

    /**
     * JSON document containing the API swagger definition.
     * Download internal/api/gen/http/openapi.json
     */
    async swaggerSwaggerSwaggerJsonRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/swagger/swagger.json`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * JSON document containing the API swagger definition.
     * Download internal/api/gen/http/openapi.json
     */
    async swaggerSwaggerSwaggerJson(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.swaggerSwaggerSwaggerJsonRaw(initOverrides);
    }

}
