on:
  pull_request:
  push:
    branches:
    - main
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Install bingo
      run:
        go install github.com/bwplotka/bingo@latest
    - name: Install golangci-lint
      run:
        echo $(go env GOPATH)/bin >> $GITHUB_PATH
        bingo get -l golangci-lint
    - name: Lint code
      run:
        echo $(go env GOPATH)/bin >> $GITHUB_PATH
        golangci-lint run -v --timeout=5m
