on:
  pull_request:
  push:
    branches:
      - main
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read Go version
        id: go_version
        run: echo "go_version=$(cat .go-version)" >> $GITHUB_OUTPUT
      - name: Install Go (${{ steps.go_version.outputs.go_version }})
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go_version.outputs.go_version }}
      - name: Install golangci-lint
        run: |
          echo $(go env GOPATH)/bin >> $GITHUB_PATH
          echo $PATH
          make bingo
          bingo get -l golangci-lint
      - name: Lint code
        run: echo $(go env GOPATH)/bin >> $GITHUB_PATH
          make lint
