on:
  pull_request:
  push:
    branches:
      - main
name: Mod
jobs:
  mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Check go.mod
        run: |
          go mod tidy
          if [ ! -z "$(git status --porcelain go.mod)" ]; then
            printf "go.mod has modifications\n"
            git diff go.mod
            exit 1
          fi
          if [ ! -z "$(git status --porcelain go.sum)" ]; then
            printf "go.sum has modifications\n"
            git diff go.sum
            exit 1
          fi
