name: Nightly

on:
  workflow_dispatch: {}
  schedule:
    # Daily, at 1pm UTC / 6am PST.
    - cron: "0 13 * * *"

jobs:
  govulncheck:
    name: Go vulnerability check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-file: go.mod
