on:
  pull_request:
  push:
    branches:
      - main
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Read Go version
        id: go_version
        run: echo "go_version=$(cat .go-version)" >> $GITHUB_OUTPUT
      - name: Install Go (${{ steps.go_version.outputs.go_version }})
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go_version.outputs.go_version }}
      - name: Test
        run: make test-ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: covreport
