// tslint:disable
// eslint-disable
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EnduroStoredCollectionResponseBodyCollection,
    EnduroStoredCollectionResponseBodyCollectionFromJSON,
    EnduroStoredCollectionResponseBodyCollectionFromJSONTyped,
    EnduroStoredCollectionResponseBodyCollectionToJSON,
} from './';

/**
 * 
 * @export
 * @interface CollectionListResponseBody
 */
export interface CollectionListResponseBody {
    /**
     * 
     * @type {EnduroStoredCollectionResponseBodyCollection}
     * @memberof CollectionListResponseBody
     */
    items: EnduroStoredCollectionResponseBodyCollection;
    /**
     * 
     * @type {string}
     * @memberof CollectionListResponseBody
     */
    nextCursor?: string;
}

export function CollectionListResponseBodyFromJSON(json: any): CollectionListResponseBody {
    return CollectionListResponseBodyFromJSONTyped(json, false);
}

export function CollectionListResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionListResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': EnduroStoredCollectionResponseBodyCollectionFromJSON(json['items']),
        'nextCursor': !exists(json, 'next_cursor') ? undefined : json['next_cursor'],
    };
}

export function CollectionListResponseBodyToJSON(value?: CollectionListResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': EnduroStoredCollectionResponseBodyCollectionToJSON(value.items),
        'next_cursor': value.nextCursor,
    };
}


