// tslint:disable
// eslint-disable
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Collection not found
 * @export
 * @interface CollectionRetryNotFoundResponseBody
 */
export interface CollectionRetryNotFoundResponseBody {
    /**
     * Identifier of missing collection
     * @type {number}
     * @memberof CollectionRetryNotFoundResponseBody
     */
    id: number;
    /**
     * Message of error
     * @type {string}
     * @memberof CollectionRetryNotFoundResponseBody
     */
    message: string;
}

export function CollectionRetryNotFoundResponseBodyFromJSON(json: any): CollectionRetryNotFoundResponseBody {
    return CollectionRetryNotFoundResponseBodyFromJSONTyped(json, false);
}

export function CollectionRetryNotFoundResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionRetryNotFoundResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
    };
}

export function CollectionRetryNotFoundResponseBodyToJSON(value?: CollectionRetryNotFoundResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'message': value.message,
    };
}


